### PR TITLE
fix: Do not change readonly id when deleting (#9538)

### LINKED ISSUE #9538: Bug: UnitOfWork try to set null to  a read-only id column after remove
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.11.1
| PHP Version     | 8.1.1

#### Summary

I have a entity with a read-only id property, and when a try to remove the entry a receive a LogicException.  `Attempting to change readonly property App\Entity\Supplier::$id.`

#### Current behavior

The UnitOfWork always try to set the id of entity to null when it' executes the `executeDeletions` method. https://github.com/doctrine/orm/blob/ed50e3d9671e26857da6897c8e9323e78f6e34c1/lib/Doctrine/ORM/UnitOfWork.php#L1254-L1256

#### How to reproduce

```php
#[ORM\Entity]
class Supplier
{
    #[ORM\Id]
    #[ORM\Column(name: 'id', type: 'integer', nullable: false)]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    public readonly int $id;

    public function __construct(
        #[ORM\Column(nullable: false)]
        public readonly string $name,
    ) {}
}
```

```php
$entityManager->find(Supplier::class, 1);
$entityManager->remove($entity);
$entityManager->flush($entity);
```

#### Expected behavior

Delete the entry from database, but i dont know what's the expected behavior to the orm internals.

### PR DESCRIPTION
**Pull request by robske110**
Fixes #9538 by not resetting the ID of objects which have a readonly identifier to null.
This will cause those to not be seen as new objectes (will be STATE_DETACHED). However, this is in my understanding not a problem as entities with readonly ID cannot be reused anyways.
If those need to be seen as NEW for some practical reason, we could also persist the NEW state in entityStates (which the commented line just above the resetting does).

Additional notes:
From the commit commenting that line out, it is not entirely clear to me why that change was made (setting id to null rather than persisting the state). Persisting the state instead of setting the id to null does not seem to cause any trouble with all tests passing (apart from maybe a slight memory leak).

This does not touch the issues #9505.

### CODE REVIEW

**Comment by greg0ire** [comment]
> From the commit commenting that line out

Link for the lazy: 4212b88edcf07288ea9fd301047b0025732169a0

> it is not entirely clear to me why that change was made (setting id to null rather than persisting the state)

I asked my LLM, it says that it's

>  because the state is now fully unset() instead, which is safer against spl_object_hash reuse. The getEntityState() method can dynamically infer STATE_NEW when needed, so explicitly storing it was both unnecessary and a potential source of bugs.

And indeed, in the diff above, you can see that `$this->entityStates[$oid]` is included in a call to `unset()`. Having it unset leads to this piece of code, which correctly assume that it was either new or detached

https://github.com/doctrine/orm/blob/580a95ce3f5f016547d15ecc6cc94dd85453bed5/src/UnitOfWork.php#L1629

File: src/UnitOfWork.php [hunk 1]
```diff
@@ -1176,7 +1177,11 @@ private function executeDeletions(): void
             // Entity with this $oid after deletion treated as NEW, even if the $oid
             // is obtained by a new entity because the old one went out of scope.
             //$this->entityStates[$oid] = self::STATE_NEW;
-            if (! $class->isIdentifierNatural()) {
+            if (
+                ! $class->isIdentifierNatural() && ! (
+                $class->propertyAccessors[$class->identifier[0]] instanceof ReadonlyAccessor &&
+                $class->propertyAccessors[$class->identifier[0]]->getUnderlyingReflector()->isInitialized($entity))
```
Comment (greg0ire) [inline src/UnitOfWork.php]: My LLM tells me that this condition is unnecessary, and when I remove it the tests pass. Is there are point to this condition? If there is, please write a failing test.

> If the property is not initialized, ReadonlyAccessor::setValue() would already succeed (it delegates to the parent accessor when uninitialized). So the guard is being extra cautious -- but in the deletion path, the entity was previously managed and flushed, meaning the ID was always initialized. The check doesn't hurt, but it adds complexity for a case that can't actually occur in this code path.

Comment (robske110) [reply src/UnitOfWork.php]: Yes, there is not a testcase I can think of that would necessitate the isInitialized condition and there should indeed be no code path that allows the id to be not initialized here. Removing the check.

**Comment by robske110** [comment]
To answer to your comment regarding my additional notes:
(All of this is not really relevant to this PR specifically, but still an interesting dicussion and prompted me to look at all of this a bit closer.)

I think the reason the LLM provided doesn't really make sense.
> because the state is now fully unset() instead, which is safer against spl_object_hash reuse

We're actually using spl_object_id here (but it has the same reuse behavior). However, reuse can in my opinion not lead to additional bugs, as if the object id will be reused, that object obviously should also be initially in STATE_NEW - and that's now just still cached. Now re-reading the comments above the commented line, it actually explictly mentions this.
_After some more digging:_ Technically this would however prevent the new object from being seen as DETACHED until it became managed before. But to reproduce this, oid reuse isn't even necesarry! (You can simply re-set an id on a deleted entity.) So this might have been the actual reason the change was made. However, see at the end of this comment for more on this.

Also: Because this project now requires PHP 8 this could all be rewritten to use a WeakMap anyways if we for some reason that's not yet obvious to me need/want to start storing the state again. This also gets rid of multiple "memory leaks", and the reuse "issue", but it would not solve the DETACHED state not being possible.

And on that DETACHED state:
Actually it looks like that at this point the distinction between NEW and DETACHED is potentially not even _really_ required anymore: Setting the value of STATE_DETACHED to 2 (STATE_NEW) doesn't result in any test failures, and with this you can even remove the ID to null change in executeDeletions and everything still passes. This would still be a somewhat breaking API change at the very least though.
And the test suite might also simply not be comprehensive enough here. (It definetly doesn't validate some things, for example the code path to throw an exception on attempting to delete detached entities is never tested.)

**Comment by robske110** [comment]
Let me know if this PR otherwise looks good now with the simplified check, then I can squash the two commits together.

**Review by greg0ire — APPROVED** [review]
It is looking good, yes

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @robske110 !
