### PR TITLE
Escape library as a table name in tests (#12170)

### LINKED ISSUE #12170: Test suite incompatibility with MySQL 9.4: LIBRARY is a reserved word
### Bug Report

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 2.2.x 

#### Summary

Apparently since MySQL 9.4 "LIBRARY" is a reserved SQL word, so the Library Enum in the test suite is causing an SQL error:
```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Library (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET' at line 1' while executing DDL: CREATE TABLE Library (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
```

I was about to send a PR, but TBH I'm not sure if the driver should manage quoting the table name in case it's a reserved word, or if the entity should simply use a different table name.

#### Current behavior

1) Doctrine\Tests\ORM\Functional\EnumTest::testEnumCollectionMatchingOnOneToMany with data set #0 (Doctrine\Common\Collections\Expr\Comparison Object (...))
Doctrine\ORM\Tools\ToolsException: Schema-Tool failed with Error 'An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Library (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET' at line 1' while executing DDL: CREATE TABLE Library (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB

#### Expected behavior

Test(s) pass

#### How to reproduce

Run test suite with MySQL 9.4

### PR DESCRIPTION
**Pull request by mbeccati**
It is a reserved word since MySQL 9.2:
https://dev.mysql.com/doc/refman/9.2/en/create-library.html

Fixes #12170

### CODE REVIEW

File: tests/Tests/Models/Enums/Library.php [hunk 1]
```diff
@@ -11,8 +11,10 @@
 use Doctrine\ORM\Mapping\GeneratedValue;
 use Doctrine\ORM\Mapping\Id;
 use Doctrine\ORM\Mapping\OneToMany;
+use Doctrine\ORM\Mapping\Table;
 
 #[Entity]
+#[Table('library1')]
```
Comment (greg0ire) [inline tests/Tests/Models/Enums/Library.php]: Would the following fix the issue?

```suggestion
#[Table('`library`')]
```

[The docs](https://www.doctrine-project.org/projects/doctrine-orm/en/3.5/reference/basic-mapping.html#quoting-reserved-words) suggest it would.

Comment (mbeccati) [reply tests/Tests/Models/Enums/Library.php]: Yes, indeed.
I had seen backticks used in definitions, but I always thought it was because the underlying platform was MySQL, as double quotes are the SQL standard for quoting identifiers. Thanks!

**Review by greg0ire — APPROVED** [review]

**Comment by mpdude** [comment]
Nit-picking: More correct would it be to title the PR as "Escape `library` as a table name" or similar. We are not avoiding the name, after all, and not forbidding or recommending users to use it either.

**Review by mpdude — APPROVED** [review]
