### PR TITLE
Make error message suggestion accurate

### LINKED ISSUE #9536: Misleading error message for bi-dir O:O with no mappedBy
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.11.1

#### Summary
Wrong validation message is displayed when an incorrect bidirectional one-to-one mapping is set up. When the owning side is configured correctly and the target side is missing the back reference the ORM suggests adding `inverseBy` instead of `mappedBy`.

I may be wrong, but adding such `inversedBy` creates another error in the mapping, while using `mappedBy` results in mapping passing the validation.

#### Current behavior

```
Mapping
-------

 [FAIL] The entity-class App\Entity\Media mapping is invalid:
 * The field App\Entity\Media#attachment is on the owning side of a bi-directional relationship, but the specified mappedBy association on the target-entity App\Entity\Attachment# does not contain the required 'inversedBy' attribute.
```

#### How to reproduce
1. Configure two entities like so:

```php
#[ORM\Entity]
class Media
{
    //...
    #[ORM\OneToOne(inversedBy: 'media')]
    #[ORM\JoinColumn(name: 'ZTH1', referencedColumnName: 'ZPK')]
    private Attachment $attachment;
}

#[ORM\Entity]
class Attachment
{
    #[ORM\OneToOne]
    #[ORM\JoinColumn(name: 'ZMD0', referencedColumnName: 'ZPK')]
    private ?Media $media;
```

2. Run `bin/console doctrine:schema:validate`

#### Expected behavior

I believe that the message should suggest adding `mappedBy` and not `inversedBy`, as [according to the docs](https://www.doctrine-project.org/projects/doctrine-orm/en/2.11/reference/association-mapping.html#one-to-one-bidirectional), the owning side needs `inversedBy` while the target side uses `mappedBy`. In addition it seems like the target entity reference should contain a field which is missing (nothing after `#`).

With both fixed the message will look like the following:
```
 [FAIL] The entity-class App\Entity\Media mapping is invalid:
 * The field App\Entity\Media#attachment is on the owning side of a bi-directional relationship, but the specified mappedBy association on the target-entity App\Entity\Attachment#media does not contain the required 'mappedBy' attribute.
```

See PR https://github.com/doctrine/orm/pull/9537

### PR DESCRIPTION
**Pull request by kiler129**
Wrong validation message is displayed when an incorrect bidirectional
one-to-one mapping is set up. When the owning side is configured
correctly and the target side is missing the back reference the ORM
suggests adding inverseBy instead of mappedBy, with the field name
missing.

Fixes https://github.com/doctrine/orm/issues/9536

### CODE REVIEW

File: lib/Doctrine/ORM/Tools/SchemaValidator.php [hunk 1]
```diff
@@ -134,9 +134,9 @@ public function validateClass(ClassMetadataInfo $class)
                             'field ' . $assoc['targetEntity'] . '#' . $assoc['inversedBy'] . ' which does not exist.';
                 } elseif ($targetMetadata->associationMappings[$assoc['inversedBy']]['mappedBy'] === null) {
                     $ce[] = 'The field ' . $class->name . '#' . $fieldName . ' is on the owning side of a ' .
-                            'bi-directional relationship, but the specified mappedBy association on the target-entity ' .
-                            $assoc['targetEntity'] . '#' . $assoc['mappedBy'] . ' does not contain the required ' .
-                            "'inversedBy' attribute.";
+                            'bi-directional relationship, but the specified inversedBy association on the target-entity ' .
+                            $assoc['targetEntity'] . '#' . $assoc['inversedBy'] . ' does not contain the required ' .
+                            "'mappedBy' attribute.";
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Tools/SchemaValidator.php]: Another way to confirm that you are correct is to look at the block on line 114, which should be a mirror of this one.

**Review by greg0ire — COMMENTED** [review]
Please write a unit test for this in `tests/Doctrine/Tests/ORM/Tools/SchemaValidatorTest.php`

File: lib/Doctrine/ORM/Tools/SchemaValidator.php (hunk 1 above)
Comment (kiler129) [reply lib/Doctrine/ORM/Tools/SchemaValidator.php]: That's why I was thinking. I think tripped over that message long time ago and now I did it again, but this time I decided to fix it :)

File: tests/Doctrine/Tests/ORM/Tools/SchemaValidatorTest.php [hunk 2]
```diff
@@ -435,6 +454,46 @@ class DDC3274Two
...
+    /**
+     * @var mixed
+     * @Id
+     * @Column
+     * @GeneratedValue
+     */
+    private $id;
+
+    /**
+     * @var ArrayCollection
```
Comment (greg0ire) [inline tests/Doctrine/Tests/ORM/Tools/SchemaValidatorTest.php]:
```suggestion
     * @var Issue9536Owner
```

Comment (kiler129) [reply tests/Doctrine/Tests/ORM/Tools/SchemaValidatorTest.php]: Thank you for your patience - fixed ;)

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @kiler129 !
