### PR TITLE
Deprecate ClassMetadata::$reflFields

### LINKED ISSUE #12082: Access to ClassMetadata::$reflFields is deprecated
### Bug Report

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 3
| Previous Version if the bug is a regression | x.y.z

#### Summary

Internal deprecation leak.

#### Current behavior

We're seeing internal deprecations to doctrine:

```
context_exception_message
User Deprecated: Access to ClassMetadata::$reflFields is deprecated and will be removed in Doctrine ORM 4.0. (LegacyReflectionFields.php:59 called by ClassMetadata.php:599, https://github.com/doctrine/orm/pull/11659, package doctrine/orm)

context_exception_trace
vendor/doctrine/deprecations/src/Deprecation.php:108
vendor/doctrine/orm/src/Mapping/LegacyReflectionFields.php:59
vendor/doctrine/orm/src/Mapping/ClassMetadata.php:599
```

#### Expected behavior

no deprecation

### PR DESCRIPTION
**Pull request by greg0ire**
It is replaced with property accessors since
https://github.com/doctrine/orm/pull/11659

Fixes #12082

### CODE REVIEW

File: src/Mapping/ClassMetadata.php [hunk 1]
```diff
@@ -604,7 +610,11 @@ public function getPropertyAccessor(string $name): PropertyAccessor|null
         return $this->propertyAccessors[$name] ?? null;
     }
 
-    /** @throws BadMethodCallException If the class has a composite identifier. */
+    /**
+     * @deprecated Use getPropertyAccessor() instead.
+     *
+     * @throws BadMethodCallException If the class has a composite identifier.
+     */
     public function getSingleIdReflectionProperty(): ReflectionProperty|null
```
Comment (greg0ire) [inline src/Mapping/ClassMetadata.php:618]: Let me know if you think an equivalent method should be introduced.

**Review by ro0NL — COMMENTED** [review]
Im curious if this could be considered a patch release, to send out better public API deprecations, for what is already triggering confusing internal deprecations.

**Comment by greg0ire** [comment]
@ro0NL I think you're right, let me retarget.

File: UPGRADE.md [hunk 2]
```diff
@@ -69,6 +69,8 @@ that implements `ArrayAccess`.
 Use the new `Doctrine\ORM\Mapping\PropertyAccessors\PropertyAccessor` API and access
 through `Doctrine\ORM\Mapping\ClassMetadata::$propertyAccessors` instead.
 
+Companion accessor methods are deprecated as well.
```
Comment (ro0NL) [inline UPGRADE.md:72]: maybe even target 3.4 then ;)

Comment (greg0ire) [reply UPGRADE.md:72]: It's too late for that, the branch does not exist anymore (and even if it did, it's no longer maintained).

**Review by beberlei — APPROVED** [review]

**Review by SenseException — APPROVED** [review]
