### PR TITLE
Fix initializing lazy objects and get rid of "Typed property must not be accessed before initialization" errors

### LINKED ISSUE #10336: Clearing the em before accessing an uninitialized relation results in "typed property must not be accessed before initialization..." error
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.14.0

#### Summary

Consider the following code:

```php
$results = $repo->createQueryBuilder('e')
    ->innerJoin('e.relation', 'r')
    ->getQuery()
    ->execute()
;

$em->clear();

echo $results[0]->relation->value;
```

#### Previous behavior

In 2.13.5, would echo the relation's value property.

#### Current behavior

In 2.14.0:

> Error: Typed property Relation::$value must not be accessed before initialization

@nicolas-grekas, could this be related to #10187?

Reproducer: #10337

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Fix #10336

### CODE REVIEW

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH10336Test.php [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+declare(strict_types=1);
+
+namespace Doctrine\Tests\ORM\Functional\Ticket;
+
+use Doctrine\Tests\Models\GH10336\GH10336Entity;
+use Doctrine\Tests\Models\GH10336\GH10336Relation;
+use Doctrine\Tests\OrmFunctionalTestCase;
+
+/**
+ * @requires PHP 8.0
```
Comment (kbond) [inline tests/Doctrine/Tests/ORM/Functional/Ticket/GH10336Test.php]:
```suggestion
 * @requires PHP 7.4
```

**Comment by simonberger** [comment]
Where is the point in taking my fix and implement it in just a different coding style?
https://github.com/doctrine/orm/pull/10362

**Comment by nicolas-grekas** [comment]
No specific point, I just missed your PR sorry, thanks for point at it.
Now that I compared both, I find the code style easier to follow in this very PR. WDYT?

**Comment by pableu** [comment]
@simonberger closed #10362, so let's get this one merged :-)

**Comment by bendavies** [comment]
LGTM, fixes my similar issue. thanks NG.

File: lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php [hunk 2]
```diff
@@ -165,6 +165,10 @@ protected function hydrateRowData(array $row, array &$result)
             }
         }
 
+        if (isset($this->_hints[Query::HINT_REFRESH_ENTITY])) {
+            $this->registerManaged($this->class, $this->_hints[Query::HINT_REFRESH_ENTITY], $data);
+        }
+
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php:171]: These lines were removed in https://github.com/doctrine/orm/pull/10187 as pointed out in https://github.com/doctrine/orm/issues/10336#issuecomment-1368578980

File: lib/Doctrine/ORM/Proxy/ProxyFactory.php [hunk 3]
```diff
@@ -313,17 +314,24 @@ private function generateSkippedProperties(ClassMetadata $class): string
...
 
-            $prefix = $property->isPrivate() ? "\0" . $property->getDeclaringClass()->getName() . "\0" : ($property->isProtected() ? "\0*\0" : '');
+                $prefix = $property->isPrivate() ? "\0" . $property->getDeclaringClass()->getName() . "\0" : ($property->isProtected() ? "\0*\0" : '');
+
+                $skippedProperties[$prefix . $name] = true;
+            }
 
-            $skippedProperties[$prefix . $name] = true;
+            $filter    = ReflectionProperty::IS_PRIVATE;
+            $reflector = $reflector->getParentClass();
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Proxy/ProxyFactory.php:334]: This seems to do the same as before, but for does it also for ancestors in the class hierarchy, retrieving only private properties for those (I guess public and protected are already retrieved at the first iteration because they are inherited).

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH10336Test.php [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+        $this->_em->persist($relation);
+        $this->_em->flush();
+        $this->_em->clear();
+
+        $entity = $this->_em->find(GH10336Entity::class, 1);
+
+        $this->_em->clear();
+
+        $this->assertSame('foo', $entity->relation->value);
+    }
```
Comment (greg0ire) [inline tests/Doctrine/Tests/ORM/Functional/Ticket/GH10336Test.php:43]: Although this test 100% covers this change, the `while` loop only ever does one iteration. Yet when I use `git restore --source=origin/2.14.x lib/Doctrine/ORM/Proxy/ProxyFactory.php`, a preexisting test fails `Doctrine\Tests\ORM\Functional\MappedSuperclassTest::testCRUD`, which means the scenario where there is more than 1 iteration is already covered 👍

It gets broken by the changes in `SimpleObjectHydrator`, and fixed by the changes in `ProxyFactory`

**Review by greg0ire — APPROVED** [review]
Looks good because there are more tests, but don't ask me to explain this change :sweat_smile: If somebody can help me figure it out, I might feel confident enough to merge.

**Review by stof — APPROVED** [review]
