### PR TITLE
[GH-8137] Update doctrine/inflector dependency to 1.4|2.0

### LINKED ISSUE #8137: Deprecation notices from doctrine/inflector 1.4
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.7/2.8.x

#### Summary

The old inflector API is deprecated since `doctrine/inflector` 1.4.

The new API is available in inflector 1.4. The new API should be used for 2.7/2.8 and master. See https://github.com/doctrine/common/issues/889

#### Current behavior

The following deprecation is triggered by https://github.com/doctrine/orm/blob/2.7/lib/Doctrine/ORM/EntityRepository.php#L305

    The "Doctrine\Common\Inflector\Inflector::classify" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector 
API.

#### How to reproduce

Just install this package together with `doctrine/inflector` 1.4.

#### Expected behavior

No deprecation should be triggered

### PR DESCRIPTION
**Pull request by beberlei**
Resolve the deprecations by instantiating default inflector.

This cannot go into 2.7, because it would raise PHP dependency from 7.1 to 7.2.

Fixes #8137

### CODE REVIEW

File: lib/Doctrine/ORM/EntityRepository.php [hunk 1]
```diff
@@ -57,6 +57,11 @@ class EntityRepository implements ObjectRepository, Selectable
      */
     protected $_class;
 
+    /**
+     * @var \Doctrine\Inflector\Inflector
```
Comment (greg0ire) [inline lib/Doctrine/ORM/EntityRepository.php:61]:
```suggestion
     * @var Inflector
```

File: lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php [hunk 2]
```diff
@@ -79,12 +80,18 @@ class DatabaseDriver implements MappingDriver
      */
     private $namespace;
 
+    /**
+     * @var \Doctrine\Inflector\Inflector
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php:84]:
```suggestion
     * @var Inflector
```

File: lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php [hunk 3]
```diff
@@ -79,12 +80,18 @@ class DatabaseDriver implements MappingDriver
...
+     */
+    protected $inflector;
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php:86]: Since there is an accessor, it can (and should?) be private

```suggestion
    private $inflector;
```

File: lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php [hunk 4]
```diff
@@ -168,6 +175,16 @@ public function setTables($entityTables, $manyToManyTables)
...
     }
 
+    public function setInflector(Inflector $inflector) : void
+    {
+        $this->inflector = $inflector;
+    }
+
+    public function getInflector() : Inflector
+    {
+        return $this->Inflector;
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php:185]: Inflector is badly inflected here :P
```suggestion
        return $this->inflector;
```

File: lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php [hunk 5]
```diff
@@ -168,6 +175,16 @@ public function setTables($entityTables, $manyToManyTables)
         }
     }
 
+    public function setInflector(Inflector $inflector) : void
+    {
+        $this->inflector = $inflector;
+    }
+
+    public function getInflector() : Inflector
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php:183]: Shouldn't it be final?
```suggestion
    final public function getInflector() : Inflector
```

File: lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php [hunk 6]
```diff
@@ -168,6 +175,16 @@ public function setTables($entityTables, $manyToManyTables)
...
+    {
+        return $this->Inflector;
+    }
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php:186]: Do we really need both of these accessors?

File: lib/Doctrine/ORM/Tools/EntityGenerator.php [hunk 7]
```diff
@@ -335,6 +336,11 @@ public function __construct(<params>)
 }
 ';
 
+    /**
+     * @var \Doctrine\Inflector\Inflector
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Tools/EntityGenerator.php:340]:
```suggestion
     * @var Inflector
```

File: lib/Doctrine/ORM/Tools/EntityGenerator.php [hunk 8]
```diff
@@ -335,6 +336,11 @@ public function __construct(<params>)
...
+     */
+    protected $inflector;
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Tools/EntityGenerator.php:342]:
```suggestion
    private $inflector;
```

File: lib/Doctrine/ORM/Tools/EntityGenerator.php [hunk 9]
```diff
@@ -592,6 +600,16 @@ public function setBackupExisting($bool)
...
     }
 
+    public function setInflector(Inflector $inflector) : void
+    {
+        $this->inflector = $inflector;
+    }
+
+    public function getInflector() : Inflector
+    {
+        return $this->Inflector;
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Tools/EntityGenerator.php:610]:
```suggestion
        return $this->inflector;
```

File: lib/Doctrine/ORM/Tools/EntityGenerator.php [hunk 10]
```diff
@@ -592,6 +600,16 @@ public function setBackupExisting($bool)
         $this->backupExisting = $bool;
     }
 
+    public function setInflector(Inflector $inflector) : void
+    {
+        $this->inflector = $inflector;
+    }
+
+    public function getInflector() : Inflector
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Tools/EntityGenerator.php:608]:
```suggestion
    final public function getInflector() : Inflector
```

File: lib/Doctrine/ORM/Tools/EntityGenerator.php [hunk 11]
```diff
@@ -592,6 +600,16 @@ public function setBackupExisting($bool)
...
+    {
+        return $this->Inflector;
+    }
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Tools/EntityGenerator.php:611]: Same question here: why expose this internal to the outside world?

File: lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php (hunk 5 above)
Comment (beberlei) [reply lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php:183]: i removed the getters now

File: lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php (hunk 3 above)
Comment (beberlei) [reply lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php]: No, in this case its used from protected methods, maybe someone overwrites them and needs access.

File: lib/Doctrine/ORM/Tools/EntityGenerator.php (hunk 8 above)
Comment (beberlei) [reply lib/Doctrine/ORM/Tools/EntityGenerator.php:342]: No, in this case its used from protected methods, maybe someone overwrites them and needs access.

File: lib/Doctrine/ORM/EntityRepository.php [hunk 12]
```diff
@@ -57,6 +58,9 @@ class EntityRepository implements ObjectRepository, Selectable
      */
     protected $_class;
 
+    /** @var Inflector */
```
Comment (beberlei) [inline lib/Doctrine/ORM/EntityRepository.php:61]: @greg0ire i really have to stop using Vim to do my Doctrine changes :) I don't have inflector type imported already, is it really necessary to make the use statement just for the docblock? seems excessive :)

File: lib/Doctrine/ORM/Tools/EntityGenerator.php (hunk 8 above)
Comment (greg0ire) [reply lib/Doctrine/ORM/Tools/EntityGenerator.php:340]: Maybe we could make the protected methods final?

File: lib/Doctrine/ORM/EntityRepository.php (hunk 12 above)
Comment (greg0ire) [reply lib/Doctrine/ORM/EntityRepository.php]: I use Vim too, and it is absolutely terrific! Just make sure you use `phpactor` with it, and use `:PhpactorImportClass` ;) My vimrc is here if you want to take a look: https://github.com/greg0ire/dotvim/blob/master/vimrc

> I don't have inflector type imported already, is it really necessary to make the use statement just for the docblock? seems excessive :)

I don't make the rules, it's our coding standard… anyway, the docblock will become a type in php 7.4, which means we will end up importing the use statement if we didn't already. Let's do it now, it's just less work.

**Review by greg0ire — APPROVED** [review]
