### PR TITLE
Make it possible to have non-NULLable self-referencing associations when using application-provided IDs

### LINKED ISSUE #7877: Extra update for self-referencing Many-To-One with NONE generator strategy during persist
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.4

#### Summary

Using a self-referencing entity with a Many-To-One relationship set during the `__construct()` call with a `NONE` strategy for id generation leads to two queries:
- first an INSERT
- then an UPDATE for the relationship

#### Current behavior

- this requires the relationship related column to accept `NULL` for the first `INSERT`

`[2019-10-23 16:04:21] doctrine.DEBUG: INSERT INTO organization (id, legal_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?) {"1":"[object] (Ramsey\\Uuid\\Uuid: \"c68555b0-f5ae-11e9-914e-38baf82a0624\")","2":null} []`

- this leads to a useless `UPDATE` query

`[2019-10-23 16:04:21] doctrine.DEBUG: UPDATE organization SET legal_parent_id = ? WHERE id = ? ["[object] (Ramsey\\Uuid\\Uuid: \"c68555b0-f5ae-11e9-914e-38baf82a0624\")","[object] (Ramsey\\Uuid\\Uuid: \"c68555b0-f5ae-11e9-914e-38baf82a0624\")"] []`

#### How to reproduce

```sql

CREATE TABLE `organization` (
  `id` binary(16) NOT NULL COMMENT '(DC2Type:uuid_binary_ordered_time)',
  `legal_parent_id` BINARY(16) NOT NULL COMMENT '(DC2Type:uuid_binary_ordered_time)',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_C1EE637C9EB3F521 FOREIGN KEY (legal_parent_id) REFERENCES organization (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

```

```php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * An Organization
 * @ORM\Entity(repositoryClass="App\Repository\OrganizationRepository")
 */
class Organization
{
    public function __construct()
    {
        $factory = clone \Ramsey\Uuid\Uuid::getFactory();
        $codec = new \Ramsey\Uuid\Codec\OrderedTimeCodec(
            $factory->getUuidBuilder()
        );
        $factory->setCodec($codec);
		$this->id = $factory->uuid1();
        $this->legalParent = $this;
        parent::__construct();
    }

    /**
     * Unique ID of the entity
     *
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="NONE")
     * @ORM\Column(type="uuid_binary_ordered_time", unique=true)
     */
    private $id;

    public function getId(): ?string
    {
        return $this->id->__toString();
    }

    /**
     * @var self
     * @ORM\ManyToOne(targetEntity="App\Entity\Organization")
     * @ORM\JoinColumn(fieldName="legal_parent_id", referencedColumnName="id", nullable=false)
     */
    protected $legalParent;

    public function getLegalParent(): self
    {
        return $this->legalParent;
    }

    public function setLegalParent(self $legalParent): self
    {
        $this->legalParent = $legalParent;

        return $this;
    }
}

```

#### Expected behavior

- Only the `INSERT` query with `legal_parent_id` not `NULL`

`[2019-10-23 16:04:21] doctrine.DEBUG: INSERT INTO organization (id, legal_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?) {"1":"[object] (Ramsey\\Uuid\\Uuid: \"c68555b0-f5ae-11e9-914e-38baf82a0624\")","2":[object] (Ramsey\\Uuid\\Uuid: \"c68555b0-f5ae-11e9-914e-38baf82a0624\")} []`

#### Possible solution

This comes from `vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php`

image

We could check if `spl_object_hash($newVal) === spl_object_hash($entity)` and if `ClassMetadataInfo::GENERATOR_TYPE_NONE === $this->class->generatorType`. If yes, then do not set `$newVal = null;` and do not schedule extra update.

I can provide a PR if you want

### PR DESCRIPTION
**Pull request by mpdude**
This change improves scheduling of extra updates in the `BasicEntityPersister`.

Extra updates can be avoided when
* the referred-to entity has already been inserted during the current insert batch/transaction and the post-insert (database) ID is already available in the entity
* we have a self-referencing entity with application-provided ID values (the `NONE` generator strategy).

As a corollary, with this change applications that provide their own IDs can define self-referencing associations as not NULLable.

One caveat, though: In the absence of entity-level commit ordering (#10547), it is not guaranteed that entities with self-references (at the class level) will be inserted in a suitable order. The order depends on the sequence in which the entities were added with `persist()`. 

Fixes #7877, closes #7882.

Co-authored-by: Sylvain Fabre <sylvain.fabre@assoconnect.com>

### CODE REVIEW

**Comment by mpdude** [comment]
@sylfabre it ain't that simple – references between different entities also schedule extra updates, so we're not done yet.

**Comment by mpdude** [comment]
We need to process the post-insert IDs earlier: Not after executeInserts() has been finished, but rather during the execution. → #10743

File: lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php [hunk 1]
```diff
@@ -683,10 +690,37 @@ protected function prepareUpdateData($entity, bool $isInsert = false)
...
+                // that the UnitOfWork has already removed entities from its own list at the time
+                // they were passed to our addInsert() method.
+                //
+                // Then, there is one extra exception we can make: An entity that references back to itself
+                // _and_ uses an application-provided ID (the "NONE" generator strategy) also does not
+                // need the extra update, although it is still in the list of insertions itself.
+                // This looks like a minor optimization at first, but is the capstone for being able to
+                // use non-NULLable, self-referencing associations in applications that provide IDs (like UUIDs).
+                if (
+                    (isset($this->queuedInserts[$oid]) || $uow->isScheduledForInsert($newVal) || !$uow->isInIdentityMap($newVal))
```
Comment (mpdude) [inline lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:721]: This has to check the identity map once for every association value during inserts. 

Performance issue?

**Comment by mpdude** [comment]
😭 Converting to draft – using `isInIdentityMap()` is not safe. This does not guarantee that the entity has been written to the database. There are other code paths possible that make an entity end up in the map before being persisted.

**Review by derrabus — APPROVED** [review]

**Comment by sylfabre** [comment]
Thanks a lot @mpdude 💪

**Comment by mpdude** [comment]
@sylfabre could you please close #7882 and #7877 when this change here solved the issue?

Thanks!
