### PR TITLE
Fix attribute ManyToMany mapping

### LINKED ISSUE #9902: Wrong mapping for ManyToMany JoinTable fields when use attributes
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.12.3

#### Summary

I am trying to upgrade entities from annotations to attributes and got an strange behavior with ManyToMany relation. When use attributes, joinColumns and inverseJoinColumns are ignored and forced to use default field names. 

Below is correct behavior with annotation:

App\Entity\User:
```
/**
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User
{
    /**
     * @ORM\Column(name="u_id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private int $id;

    /**
     * @ORM\ManyToMany(targetEntity="Group", inversedBy="users")
     * @ORM\JoinTable(name="users_groups",
     *   joinColumns={
     *     @ORM\JoinColumn(name="ug_u_id", referencedColumnName="u_id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="ug_g_id", referencedColumnName="g_id")
     *   }
     * )
     */
    private ArrayCollection $groups;
}
```

App\EntityGroup

```
/**
 * @ORM\Table(name="group")
 * @ORM\Entity(repositoryClass="App\Repository\GroupRepository")
 */
class Group
{
    /**
     * @ORM\Column(name="g_id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private int $id;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="groups")
     */
    private ArrayCollection $users;
}
```

Migration:
```
        $this->addSql('CREATE TABLE "group" (g_id SERIAL NOT NULL, PRIMARY KEY(g_id))');
        $this->addSql('CREATE TABLE "user" (u_id SERIAL NOT NULL, PRIMARY KEY(u_id))');
        $this->addSql('CREATE TABLE users_groups (ug_u_id INT NOT NULL, ug_g_id INT NOT NULL, PRIMARY KEY(ug_u_id, ug_g_id))');
```

#### Current behavior

Wrong behavior with attributes:
App\Entity\User
```
#[ORM\Entity(repositoryClass: UserRepository::class)]
class User
{
    #[ORM\Column(name: 'u_id', type: 'integer', nullable: false)]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    private int $id;

    #[ORM\ManyToMany(targetEntity: Group::class, inversedBy: "users")]
    #[ORM\JoinTable(
        name: 'users_groups',
        joinColumns: [new ORM\JoinColumn(name: 'ug_u_id', referencedColumnName: 'u_id')],
        inverseJoinColumns: [new ORM\JoinColumn(name: 'ug_g_id', referencedColumnName: 'g_id')]
    )]
    private ArrayCollection $groups;
}
```
App\Entity\Group
```
#[ORM\Entity(repositoryClass: GroupRepository::class)]
class Group
{
    #[ORM\Column(name: 'g_id', type: 'integer', nullable: false)]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    private int $id;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: "groups")]
    private ArrayCollection $users;
}
```
Migration with ignored JoinTable fields:
```
        $this->addSql('CREATE TABLE "group" (g_id SERIAL NOT NULL, PRIMARY KEY(g_id))');
        $this->addSql('CREATE TABLE "user" (u_id SERIAL NOT NULL, PRIMARY KEY(u_id))');
        $this->addSql('CREATE TABLE users_groups (user_id INT NOT NULL, group_id INT NOT NULL, PRIMARY KEY(user_id, group_id))');
```
Generated schema causes 'Column not found' SQL errors.

#### How to reproduce

Use attributes in ManyToMany relation

#### Expected behavior

As described in example with annotation

### PR DESCRIPTION
**Pull request by BoShurik**
Fixes #9902

### CODE REVIEW

**Comment by greg0ire** [comment]
Can you please write a test for this, based on one of the examples mentioned in the issue you fix?

**Comment by BoShurik** [comment]
@greg0ire done

File: tests/Doctrine/Tests/ORM/Mapping/AttributeDriverTest.php [hunk 1]
```diff
@@ -123,6 +124,45 @@ public function testLegacyInheritance(): void
 
         self::assertTrue(is_subclass_of(AttributeDriver::class, PersistenceAnnotationDriver::class));
     }
+
+    public function testManyToManyAssociationWithNestedJoinColumns(): void
+    {
+        if (PHP_VERSION_ID < 80100) {
+            self::markTestSkipped('Does not work on PHP 8.0.* due to nested attributes missing.');
+        }
```
Comment (greg0ire) [inline tests/Doctrine/Tests/ORM/Mapping/AttributeDriverTest.php]: You can use `@requires PHP 8.1` for this.

File: tests/Doctrine/Tests/ORM/Mapping/Fixtures/AttributeEntityWithNestedJoinColumns.php [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+#[ORM\Entity]
+class AttributeEntityWithNestedJoinColumns
+{
+    /** @var int */
+    #[ORM\Id]
+    #[ORM\Column(type: 'integer')]
+    #[ORM\GeneratedValue]
+    public $id;
+
+    /** @var AttributeEntityWithNestedJoinColumns[] */
```
Comment (greg0ire) [inline tests/Doctrine/Tests/ORM/Mapping/Fixtures/AttributeEntityWithNestedJoinColumns.php]: This is not supposed to be an array, is it?

```suggestion
    /** @var Collection<AttributeEntityWithNestedJoinColumns> */
```

**Review by greg0ire — COMMENTED** [review]
I've tested locally, and the both assertions fail without your changes 👍

Please improve your commit message [according to our contributing guide](https://www.doctrine-project.org/contribute/index.html)

Right now, one has to read the code and tests to realize what's broken and how you fix it.

File: tests/Doctrine/Tests/ORM/Mapping/Fixtures/AttributeEntityWithNestedJoinColumns.php (hunk 2 above)
Comment (BoShurik) [reply tests/Doctrine/Tests/ORM/Mapping/Fixtures/AttributeEntityWithNestedJoinColumns.php]: Copy pasted from https://github.com/doctrine/orm/blob/2.15.x/tests/Doctrine/Tests/ORM/Mapping/AttributeDriverTest.php#L139. Does it make sense to change that there too?

Comment (greg0ire) [reply tests/Doctrine/Tests/ORM/Mapping/Fixtures/AttributeEntityWithNestedJoinColumns.php]: It would I suppose, but in a separate commit.

File: lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php [hunk 3]
```diff
@@ -433,6 +433,14 @@ public function loadMetadataForClass($className, PersistenceClassMetadata $metad
...
                         $joinTable['options'] = $joinTableAttribute->options;
                     }
+
+                    foreach ($joinTableAttribute->joinColumns as $joinColumn) {
+                        $joinTable['joinColumns'][] = $this->joinColumnToArray($joinColumn);
+                    }
+
+                    foreach ($joinTableAttribute->inverseJoinColumns as $joinColumn) {
+                        $joinTable['inverseJoinColumns'][] = $this->joinColumnToArray($joinColumn);
+                    }
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php:443]: I've looked into the issue, and it looks like there is a piece of code that is just missing from this new implementation. I don't know why it was done like that, but your commit message could look like this:

```
Take into account join columns specifications.

Currently, the AttributeDriver ignores any join column attribute
specified on a many to many relationship.
Let's copy code from the AnnotationDriver to fix that.

Fixes #9902
```

Comment (greg0ire) [reply lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php:443]: It looks like some other stuff was forgotten in #8266 in this code block: d7d6b9d2c7fcfc16a6a706c78161b441aed39ffb

Comment (BoShurik) [reply lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php:443]: It was missing because php 8.0 does not support nested attributes

Comment (greg0ire) [reply lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php:443]: Ah great! That explains it fully!

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @BoShurik !
