### PR TITLE
Fix id hash of entity with enum as identifier

### LINKED ISSUE #10334: ObjectHydrator::getEntityFromIdentityMap() does not work with backed enum
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.14.0

#### Summary

I have an entity with a backed enum as primary key. When I fetch a fresh entity from the database, everything works fine. But if I try to fetch an entity that is already known in the identity map, it fails.

#### Current behavior

It cannot load an entity with backed enum as primary key from the ObjectHydrator identity map.

> Error "Object of class MyEnum could not be converted to string"

From ObjectHydrator on line 292

#### How to reproduce

We need 2 entities, with ManyToOne relation, so we can use a join in our request.
```php
enum MyEnum: string
{
    case Yellow = 'yellow';
    case Blue = 'blue';
}
```

```php
#[ORM\Entity, ORM\Table(name: 'foo')]
class Foo
{
    #[ORM\Id, ORM\ManyToOne(inversedBy: 'foos'), ORM\JoinColumn(nullable: false)]
    private readonly FooCollection $collection;

    #[ORM\Id, ORM\Column]
    private readonly MyEnum $myEnum;
}
```

```php
#[ORM\Entity, ORM\Table(name: 'foo_collection')]
class FooCollection
{
    #[ORM\Id, ORM\Column]
    private int $id;

    /** @var Collection<int, Foo> */
    #[ORM\OneToMany(targetEntity: Foo::class, mappedBy: 'collection')]
    private Collection $foos;
}
```

```mysql
create table foo_collection
(
    id int not null primary key
);

create table foo
(
    collectionId int          not null,
    myEnum       varchar(255) not null,
    primary key (collectionId, myEnum),
    constraint foo_collection_id_fk
        foreign key (collectionId) references foo_collection (id)
);

INSERT INTO foo_collection (id) VALUES (1);
INSERT INTO foo (collectionId, myEnum) VALUES (1, 'yellow'), (1, 'blue');
```

And then, just run 2 queries to trigger the loading from the identity map
```php
    public function test(EntityManagerInterface $entityManager): void
    {
        $entityManager
            ->getRepository(FooCollection::class)
            ->createQueryBuilder('collection')
            ->leftJoin('collection.foos', 'foo')->addSelect('foo')
            ->getQuery()
            ->getResult();

        $entityManager
            ->getRepository(FooCollection::class)
            ->createQueryBuilder('collection')
            ->leftJoin('collection.foos', 'foo')->addSelect('foo')
            ->getQuery()
            ->getResult();
    }
```

#### Expected behavior

No error

### LINKED ISSUE #10471: Fail to load entity that has enum as primary key via ManyToOne association
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.14.1

#### Summary

I have an entity "Field" that has a ManyToOne relationship to "FieldType". The ID column of FieldType is backed by a native PHP enum FieldTypeID.

I can load a FieldType entity just fine, but if I load a Field and try to access the FieldType from it, I get an error.

#### Previous behavior

This was working fine in 2.14.0

#### Current behavior

Exception is thrown:

Object of class App\\Entity\\Enum\\FieldTypeID could not be converted to string
File: vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php
Line: 1575

#### How to reproduce

```
class Field
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    #[ORM\Column(name: 'id', type: Types::INTEGER, nullable: false)]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: FieldType::class)]
    #[ORM\JoinColumn(name: 'type_id', referencedColumnName: 'id', nullable: false)]
    private FieldType $type;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?FieldType
    {
        return $this->type;
    }
}

class FieldType
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(name: 'id', type: Types::INTEGER, nullable: false, enumType: FieldTypeID::class)]
    private readonly FieldTypeID $id;

    public function getId(): int
    {
        return $this->id->value;
    }
}

enum FieldTypeID: int
{
    case FOO = 1;
    case BAR = 2;
    case BAZ = 3;
}

// accessing FieldType directly works OK
$fieldType = $doctrine->getRepository(FieldType::class)->find(1);
$id = $fieldType->getId();

// accessing via association fails
$field = $doctrine->getRepository(Field::class)->find(1);
$fieldType = $field->getType();
$id = $fieldType->getId(); // exception thrown here
```

### PR DESCRIPTION
**Pull request by Gwemox**
**Current situation**
When an entity have a backed enum as identifier, Unit Of Work tries to cast to string when generating the hash of the id.

`Error "Object of class MyEnum could not be converted to string"`

**Suggested fix**
This PR fixes the problem by adding function to get id of entity with backed enum check.

**Tests added**
It seems tests for this feature were completely missing, so I added them.

Fixes https://github.com/doctrine/orm/issues/10471 
Fixes https://github.com/doctrine/orm/issues/10334

### CODE REVIEW

**Comment by Gwemox** [comment]
Can someone validate the workflow?

**Comment by derrabus** [comment]
Right away, sorry for the delay. 😓

**Comment by Gwemox** [comment]
Thank's @derrabus !
I fixed a problem

**Comment by Gwemox** [comment]
@derrabus Does this seem correct to you?

**Comment by pierrelemee** [comment]
Hey 👋 @Gwemox I also faced this issue today (I'm glad to be part of the _composite key / enum_ enthousiasts group ✊ ) so when I was about to open a pull request I saw yours.

Good job and perfect timing! Obviously 👍  for this

**Comment by Gwemox** [comment]
@greg0ire can you review this ? Do you expect anything from me?

File: lib/Doctrine/ORM/UnitOfWork.php [hunk 1]
```diff
@@ -1584,6 +1578,50 @@ public function addToIdentityMap($entity)
         return true;
     }
 
+    /**
+     * Gets the id hash of an entity by its identifier.
+     *
+     * @param array<mixed, mixed> $identifier The identifier of an entity
```
Comment (greg0ire) [inline lib/Doctrine/ORM/UnitOfWork.php]: What's the key type for this array? It should be at least `array-key`, but maybe you can narrow it down even more. Maybe this is even a `list<mixed>`

File: lib/Doctrine/ORM/UnitOfWork.php [hunk 2]
```diff
@@ -1584,6 +1578,50 @@ public function addToIdentityMap($entity)
...
+     *
+     * @return string The entity id hash.
```
Comment (greg0ire) [inline lib/Doctrine/ORM/UnitOfWork.php:1586]: You can use a return type

File: lib/Doctrine/ORM/UnitOfWork.php [hunk 3]
```diff
@@ -1584,6 +1578,50 @@ public function addToIdentityMap($entity)
...
+     */
+    public static function getIdHashByIdentifer($identifier)
```
Comment (greg0ire) [inline lib/Doctrine/ORM/UnitOfWork.php]: Let's make this method `final` please.

Comment (greg0ire) [reply lib/Doctrine/ORM/UnitOfWork.php]: Also, it should be "Identifier" with an i

File: tests/Doctrine/Tests/Models/GH10334/GH10334FooCollection.php [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+     * @var int
+     * @Id
+     * @Column(type="integer")
+     * @GeneratedValue
+     */
+    protected $id;
+
+    /**
+     * @OneToMany(targetEntity="GH10334Foo", mappedBy="collection", cascade={"persist", "remove"})
+     * @var Collection $foos
```
Comment (greg0ire) [inline tests/Doctrine/Tests/Models/GH10334/GH10334FooCollection.php]:
```suggestion
     * @var Collection<GH10334Foo> $foos
```

File: tests/Doctrine/Tests/Models/GH10334/GH10334FooCollection.php [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+    {
+        $this->foos = new ArrayCollection();
+    }
+
+    public function getId(): int
+    {
+        return $this->id;
+    }
+
+    public function getFoos(): Collection
```
Comment (greg0ire) [inline tests/Doctrine/Tests/Models/GH10334/GH10334FooCollection.php:42]:
```suggestion
    /**
     * @return Collection<GH10334Foo>
     */
    public function getFoos(): Collection
```

File: tests/Doctrine/Tests/Models/GH10334/GH10334Product.php [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+        $this->name        = $name;
+        $this->productType = $productType;
+    }
+
+    public function getName(): string
+    {
+        return $this->name;
+    }
+
+    public function setName(string $name): void
```
Comment (greg0ire) [inline tests/Doctrine/Tests/Models/GH10334/GH10334Product.php]: Please remove any unused getter/setter

File: lib/Doctrine/ORM/UnitOfWork.php (hunk 1 above)
Comment (Gwemox) [reply lib/Doctrine/ORM/UnitOfWork.php]: PHPStan tells me it's called with an int or string key.

Comment (greg0ire) [reply lib/Doctrine/ORM/UnitOfWork.php]: Ok, then use `array-key` I guess.

**Comment by Gwemox** [comment]
Thank you for this quick review, I made the requested changes.

**Review by greg0ire — DISMISSED** [review]

**Comment by BartVanGestel** [comment]
@Gwemox @greg0ire  could you merge this PR, we currently have this exact problem and this will fix alot of unneeded persists.

**Comment by Gwemox** [comment]
> @Gwemox @greg0ire could you merge this PR, we currently have this exact problem and this will fix alot of unneeded persists.

I don't have merge rights

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Ping @SenseException @derrabus

**Review by SenseException — APPROVED** [review]

**Comment by wmouwen** [comment]
@greg0ire Could you please tag a release containing this bugfix? It is cause for major locking issues on our systems and blocking releases of our software.

2023-05-31-090211_771x294_scrot
