### PR TITLE
Quote parts of the table name

### LINKED ISSUE #12041: Invalid quoting syntax for table names/schema in SQL Server
### Bug Report

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 3.3.2
| Previous Version if the bug is a regression | 3.3.1

#### Summary

After Updating doctrine/orm from 3.3.1 to 3.3.2, I get an error when selecting from an entity with quoted table name using SQL Server platform.
I think the issue was introduced with the following feature: https://github.com/doctrine/orm/pull/11811 (its the only change made in 3.3.2).

#### Current behavior

In the logs I can see that using v3.3.2 the schema and table name is quoted as one string: `[schema.table]`. This syntax is invalid in SQL Server.

#### Expected behavior

Until v3.3.1 the schema and table names were quoted individually: `schema.[table]`. This is valid SQL Server syntax.

#### How to reproduce

Create an entity using a quoted table name.

```php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

use function uuid_create;

#[ORM\Entity]
#[ORM\Table(name: '`file`', schema: 'myschema')]
class File
{
    #[ORM\Id]
    #[ORM\Column(type: 'guid', unique: true, nullable: false)]
    private string $id;

...

}
```

### PR DESCRIPTION
**Pull request by greg0ire**
In #11811, I wrongly assumed that
`$tableName` would never contain a dot as I was not able to write a test
that caused that to happen.

The secret recipe appears to be to define a schema and to quote the
table name.

Fixes https://github.com/doctrine/orm/issues/12041

### CODE REVIEW

**Comment by greg0ire** [comment]
Fails on Postgres with:

```
1) Doctrine\Tests\ORM\Functional\GH12041Test::testSchemaGenerationWithQuotedTableNameAndSchemaName
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "myschema.file" does not exist
LINE 1: INSERT INTO "myschema.file" (id) VALUES (DEFAULT)
                    ^

/home/runner/work/orm/orm/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:72
/home/runner/work/orm/orm/vendor/doctrine/dbal/src/Connection.php:1456
/home/runner/work/orm/orm/vendor/doctrine/dbal/src/Connection.php:1392
/home/runner/work/orm/orm/vendor/doctrine/dbal/src/Statement.php:108
/home/runner/work/orm/orm/vendor/doctrine/dbal/src/Statement.php:133
/home/runner/work/orm/orm/src/Persisters/Entity/BasicEntityPersister.php:261
/home/runner/work/orm/orm/src/UnitOfWork.php:1057
/home/runner/work/orm/orm/src/UnitOfWork.php:402
/home/runner/work/orm/orm/src/EntityManager.php:268
/home/runner/work/orm/orm/tests/Tests/ORM/Functional/GH12041Test.php:31
```

https://github.com/doctrine/orm/actions/runs/16606300367/job/46978995125?pr=12088#step:7:162

Now let's attempt a fix.

**Comment by greg0ire** [comment]
Huh so now the test is fixed, bug another test introduced in 54b3c0548d952f2966e8197986002e01b3b32f96 is broken.

**Comment by greg0ire** [comment]
I'm temporarily reverting #11811 to see if that gives me a green build, I'm starting to have doubts about that.

**Comment by greg0ire** [comment]
:exploding_head: it doesn't… what the hell?

**Comment by greg0ire** [comment]
Ah no, the revert works, but for some reason, the test I'm adding has a side effect :thinking:

**Comment by greg0ire** [comment]
Ah that's because the same schema name (`myschema`) is used in both tests.

**Comment by greg0ire** [comment]
Instead of altering my new test to change the schema, I'm adding a new test case to the existing test, since it tests more things.

File: src/Mapping/DefaultQuoteStrategy.php [hunk 1]
```diff
@@ -41,9 +44,17 @@ public function getTableName(ClassMetadata $class, AbstractPlatform $platform):
             $tableName = $class->table['schema'] . '.' . $class->table['name'];
         }
```
Comment (greg0ire) [inline src/Mapping/DefaultQuoteStrategy.php:51]: Just realized this is what's causing the infamous dot. Instead of inlining `quoteIdentifier()`, let me try to modify this.

**Comment by greg0ire** [comment]
Reproduced the failure by downgrading DBAL to v3.

**Review by SenseException — DISMISSED** [review]

File: src/Mapping/DefaultQuoteStrategy.php [hunk 2]
```diff
@@ -52,7 +61,10 @@ public function getTableName(ClassMetadata $class, AbstractPlatform $platform):
     public function getSequenceName(array $definition, ClassMetadata $class, AbstractPlatform $platform): string
     {
         return isset($definition['quoted'])
-            ? $platform->quoteSingleIdentifier($definition['sequenceName'])
+            ? implode('.', array_map(
```
Comment (morozov) [inline src/Mapping/DefaultQuoteStrategy.php:64]: I have little understanding of what tradeoffs are acceptable here, so I cannot provide a reasonable feedback.

Every `implode('.', $name)` is a potential bug, which is why `quoteIdentifier()` was deprecated in the first place.

Assuming that it fixes the reported issue (which is covered by a new test), the patch looks good.

File: tests/Tests/ORM/Functional/Ticket/DDC2825Test.php [hunk 3]
```diff
@@ -42,7 +46,11 @@ public function testClassSchemaMappingsValidity(string $className, string $expec
         self::assertEquals($expectedSchemaName, $classMetadata->table['schema']);
 
         if ($this->_em->getConnection()->getDatabasePlatform()->supportsSchemas()) {
-            $fullTableName = sprintf('%s.%s', $expectedSchemaName, $expectedTableName);
+            $fullTableName = sprintf(
+                $isQuoted ? '"%s"."%s"' : '%s.%s',
+                $expectedSchemaName,
+                $expectedTableName,
+            );
         } else {
```
Comment (morozov) [inline tests/Tests/ORM/Functional/Ticket/DDC2825Test.php]: This kind of test looks... not really useful. On the one hand, it's an integration test that that covers implementation details, which in turn depend on the environment, so it's hard to reason whether it provides the right feedback or not. On the other, there are two levels of code branching (`if` and `?`), but a proper test shouldn't have any conditional logic.

Would it make sense to convert it to a unit test and make the expected values explicit?

Also, the dependency of the result on `supportsSchemas()` looks a bit inadequate. The result should depend only on the input (i.e. the class metadata).

File: src/Mapping/DefaultQuoteStrategy.php (hunk 2 above)
Comment (greg0ire) [reply src/Mapping/DefaultQuoteStrategy.php:64]: I initially wrote a separate test just for the reported issue, and the other part of the patch fixed it. This is here to fix another issue found when I decided to reuse the existing test, if I recall correctly. In any case, I think that on a patch branch, doing this is the right thing, but that on the next minor, we might want deprecate relying on that implode. This will require further analysis as to the ramification of the deprecation though.

File: tests/Tests/ORM/Functional/Ticket/DDC2825Test.php (hunk 3 above)
Comment (greg0ire) [reply tests/Tests/ORM/Functional/Ticket/DDC2825Test.php]: Good points. To elaborate on your last point, the test is skipped unless the database supports schemas: https://github.com/doctrine/orm/blob/0f32569a7a64b5d8e54aa2cecc10376c3be0db56/tests/Tests/ORM/Functional/Ticket/DDC2825Test.php#L28-L30

So it makes no sense to have this `if` statement: https://github.com/doctrine/orm/blob/0f32569a7a64b5d8e54aa2cecc10376c3be0db56/tests/Tests/ORM/Functional/Ticket/DDC2825Test.php#L44-L48 , since a41c6d32c3e18e7e5c008a7b2c64d62acf24966f

This test definitely needs some love, and I will start by removing this `if` statement.

Comment (greg0ire) [reply tests/Tests/ORM/Functional/Ticket/DDC2825Test.php]: I will look into doing the improvements you mentioned, but for now, here is a PR that addresses the issue in my last message. https://github.com/doctrine/orm/pull/12094

**Review by morozov — DISMISSED** [review]

File: tests/Tests/ORM/Functional/Ticket/DDC2825Test.php (hunk 3 above)
Comment (greg0ire) [reply tests/Tests/ORM/Functional/Ticket/DDC2825Test.php]: @morozov I did the conversion to unit tests, please take another look.

**Review by derrabus — APPROVED** [review]

**Review by morozov — APPROVED** [review]
Looks much better. Thanks!

**Comment by stlrnz** [comment]
Hey, coming from https://github.com/doctrine/orm/issues/12041, I just wanted to say thank you for your hard work to fix the issue! I really appreciate this :)
