### PR TITLE
Clone query hints and parameters in `LimitSubqueryOutputWalker` constructor

### LINKED ISSUE #11741: Fetch mode hint is ignored when using `Paginator`
### Bug Report

|    Q                                        |   A
|-------------------------------------------- | --------------
| Version                                     | 2.20.0 / 3.3.0
| Previous working version                    | 2.19.8 / 3.2.3

#### Summary

This is related to issue #11128 and PR #11445.

When a `fetch=EAGER` association is filtered using `WITH`, it raises an error unless fetch mode is overridden by calling `setFetchMode(LAZY)` over the association.

This worked well after the fix in #11445.

Somehow, in 2.20.x and 3.3.x this bug returned, partially, only when using `Paginator` with `fetchJoinCollection` parameter set to `true`.

Seems like #11188 introduced this bug.

#### Current behavior

An exception is raised even when fetch mode is overridden.

#### Expected behavior

It should work the same with or without pagination.

#### How to reproduce

See test in https://github.com/aprat84/orm/tree/gh-11741

```
vendor/bin/phpunit --filter testSubselectFetchJoinWithAllowedWhenOverriddenNotEagerPaginator

There was 1 error:

1) Doctrine\Tests\ORM\Functional\EagerFetchCollectionTest::testSubselectFetchJoinWithAllowedWhenOverriddenNotEagerPaginator
Doctrine\ORM\Query\QueryException: Associations with fetch-mode=EAGER may not be using WITH conditions in "Doctrine\Tests\ORM\Functional\EagerFetchChild#owner".
```

### PR DESCRIPTION
**Pull request by aprat84**
Fixes #11741

Should be merged up to at least v2.20.0 and v3.3.0.

The problem seems to be that `LimitSubqueryOutputWalker` clones the `Query` object, but not its hints (including the `fetchMode` hint, which causes the issue).
Don't know if cloning the parameters is really needed.
Been inspired on what the class `Paginator` does when cloning a `Query`.
Suggestions are welcome!

### CODE REVIEW

File: tests/Tests/ORM/Functional/EagerFetchCollectionTest.php [hunk 1]
```diff
@@ -96,6 +98,16 @@ public function testSubselectFetchJoinWithAllowedWhenOverriddenNotEager(): void
...
+    public function testSubselectFetchJoinWithAllowedWhenOverriddenNotEagerPaginator(): void
+    {
+        $query = $this->_em->createQuery('SELECT o, c FROM ' . EagerFetchOwner::class . ' o JOIN o.children c WITH c.id = 1');
+        $query->setMaxResults(1);
+        $query->setFetchMode(EagerFetchChild::class, 'owner', ORM\ClassMetadata::FETCH_LAZY);
+
+        $paginator = new Paginator($query, true);
+        $this->assertIsArray(iterator_to_array($paginator));
+    }
+
```
Comment (SenseException) [inline tests/Tests/ORM/Functional/EagerFetchCollectionTest.php:110]: This test doesn't look like that it is covering your changes. Your use case is that a query and dependencies of it gets cloned in the `LimitSubqueryOutputWalker`.

Comment (aprat84) [reply tests/Tests/ORM/Functional/EagerFetchCollectionTest.php:110]: Yup! This is a side effect, where paginating a query with `fetchMode` override didn't work.

I added a test case just for the code I modified.

File: tests/Tests/ORM/Tools/Pagination/LimitSubqueryOutputWalkerTest.php [hunk 2]
```diff
@@ -46,6 +46,22 @@ private function replaceDatabasePlatform(AbstractPlatform $platform): void
...
+        $query->setHint('dummy-hint', 'dummy-value');
+        $query->setCacheable(true);
+
+        $walker = new LimitSubqueryOutputWalker($query, new Query\ParserResult(), []);
+
+        self::assertTrue($walker->getQuery()->hasHint('dummy-hint'));
+        self::assertSame('dummy-value', $walker->getQuery()->getHint('dummy-hint'));
+        self::assertInstanceOf(Query\Parameter::class, $param = $walker->getQuery()->getParameter('dummy-param'));
+        self::assertSame(123, $param->getValue());
+        self::assertFalse($walker->getQuery()->isCacheable());
```
Comment (SenseException) [inline tests/Tests/ORM/Tools/Pagination/LimitSubqueryOutputWalkerTest.php]: The cloning is an essential part of your PR. Please check that both queries and their Parameter objects  aren't the same instances.

File: tests/Tests/ORM/Functional/EagerFetchCollectionTest.php (hunk 1 above)
Comment (SenseException) [reply tests/Tests/ORM/Functional/EagerFetchCollectionTest.php:110]: Thanks for adding a proper test for your use case.

I still don't understand the need for this test yet. Where does your code work with a fetchmode?

**Review by SenseException — CHANGES_REQUESTED** [review]

File: tests/Tests/ORM/Functional/EagerFetchCollectionTest.php (hunk 1 above)
Comment (aprat84) [reply tests/Tests/ORM/Functional/EagerFetchCollectionTest.php:110]: If you look at previous test `testSubselectFetchJoinWithAllowedWhenOverriddenNotEager`, it asserts that fetch-mode override is currently honored.

This is the same but using `Paginator`. IMHO this is to assure that overriding fetch-mode is always working, using pagination or not.

But I agree that maybe it is redundant, in the sense that the error was not with fetch-mode or paginator directly.

If you prefer, I'll just won't include it.

File: tests/Tests/ORM/Tools/Pagination/LimitSubqueryOutputWalkerTest.php (hunk 2 above)
Comment (aprat84) [reply tests/Tests/ORM/Tools/Pagination/LimitSubqueryOutputWalkerTest.php]: Code for cloning is copied from `\Doctrine\ORM\Tools\Pagination\Paginator::cloneQuery()`.

Added check for `Query` instances, but can't do it for `Parameter` instances, cause the way the code is, it just clones the `ArrayCollection` that contains the `Parameter` instances.

For my use case (bug), cloning the parameters or setting the cloned query as non-cacheable is really not needed. What I really need is cloning the query hints along with the query.

_I don't have the knowledge on this library to decide on this, just heard about SQLWalkers 2 days ago 😅_

Comment (SenseException) [reply tests/Tests/ORM/Tools/Pagination/LimitSubqueryOutputWalkerTest.php]: Then comparing both query instances and their `getParameters()` results would be sufficient. Just saw you already did compare the query instances, so you just need to add the second clones check.

``` php
self::assertNotSame($query->getParameters(), $walker->getQuery()->getParameters());
```

File: tests/Tests/ORM/Functional/EagerFetchCollectionTest.php (hunk 1 above)
Comment (SenseException) [reply tests/Tests/ORM/Functional/EagerFetchCollectionTest.php:110]: I found the time to checkout your branch and run the test locally to understand the need for this test and how the fetchmode affect it. The test helps to cover your changes :+1:

File: tests/Tests/ORM/Tools/Pagination/LimitSubqueryOutputWalkerTest.php (hunk 2 above)
Comment (aprat84) [reply tests/Tests/ORM/Tools/Pagination/LimitSubqueryOutputWalkerTest.php]: Done!

**Review by SenseException — APPROVED** [review]

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @aprat84 !
