### PR TITLE
#7837 paginate with custom identifier types even with enabled DQL query cache

### LINKED ISSUE #7837: Paginator breaks when DQL query is re-used with different identifier parameters that require conversion
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.4

#### Summary

#7820 and #7821 fix pagination issues happening when the paginator is relying on identifiers that require custom DBAL type conversion.

The type conversion works, but since it has been performed inside the `WhereInWalker` (to keep things a bit simpler), it is only performed when the query is in `Doctrine\ORM\Query::STATE_DIRTY`.

If the parameters are changed on a `Doctrine\ORM\Query`, the query doesn't change parser state, and therefore the `WhereInWalker` is completely skipped.

I will try to write a small reproducer and fix ASAP, hoping to not cause too big performance regressions in the ORM. I think it may come down to forcing query parsing to be repeated.

#### Current behavior

```php
$id = generateCustomId();
$a  = new A($id);

$this->em->persist($a);
$this->em->flush();

$query = $this->em->createQuery('SELECT a FROM ' . A::class);

$paginator = new Paginator($query);

$query->setFirstResult(1);

Assert::count(0, \iterator_to_array($paginator));

$query->setFirstResult(0);

Assert::same([$a], \iterator_to_array($paginator));
```

#### Expected behavior

The last assertion in the test above fails: this is an unfortunate case of mutable state shared inside `Doctrine\ORM\Query`.

### PR DESCRIPTION
**Pull request by Ocramius**
This patch enforces re-parsing of DQL queries used in the paginator internals, so that the `WhereInWalker` can correctly process query parameters after evaluating the AST structure (root expression, specifically).

While this isn't nice for performance, it is also true that the alternative approach would be to run the parsing manually on the DQL query (to extract the root of the selection) and then operating on that (this was already attempted in #7821 in doctrine/orm@39d21135490472ba31755a0259fbaf38ac453b9b).

Fixes #7837

### CODE REVIEW

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php [hunk 1]
```diff
@@ -73,6 +78,41 @@ public function testWillFindSongsInPaginator() : void
...
+
+    /** @group GH7837 */
+    public function testWillFindSongsInPaginatorEvenWithCachedQueryParsing() : void
+    {
+        $cache = $this->_em->getConfiguration()
+            ->getQueryCacheImpl();
+
+        assert($cache instanceof ClearableCache);
+
+        $cache->deleteAll();
```
Comment (ostrolucky) [inline tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php]: this is not needed

Comment (Ocramius) [reply tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php]: Sadly needed, otherwise the two tests interfere with each other

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php [hunk 2]
```diff
@@ -73,6 +78,41 @@ public function testWillFindSongsInPaginator() : void
...
+        $query = $this->_em->getRepository(GH7820Line::class)
+            ->createQueryBuilder('l')
+            ->orderBy('l.lineNumber', Criteria::ASC);
+
+        self::assertSame(
+            self::SONG,
+            array_map(static function (GH7820Line $line) : string {
+                return $line->toString();
+            }, iterator_to_array(new Paginator($query))),
+            'Paginator runs once, query cache is populated with DQL -> SQL translation'
```
[the remark this answers is not in the document]
Comment (Ocramius) [reply tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php]: Had these as comments initially: moved to assertion message on purpose, since it makes failures much more descriptive

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php (hunk 1 above)
Comment (ostrolucky) [reply tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php]: which ones? Running whole GH7820Test class runs fine for me without this statement

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php (hunk 2 above)
[the remark this answers is not in the document]
Comment (ostrolucky) [reply tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php]: But this says what happens, not what should have happened

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php [hunk 3]
```diff
@@ -73,6 +78,41 @@ public function testWillFindSongsInPaginator() : void
...
         );
     }
+
+    /** @group GH7837 */
+    public function testWillFindSongsInPaginatorEvenWithCachedQueryParsing() : void
+    {
+        $cache = $this->_em->getConfiguration()
+            ->getQueryCacheImpl();
+
+        assert($cache instanceof ClearableCache);
```
Comment (Pierstoval) [inline tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php]: Why not a PHPUnit assertion? 🤔

Comment (SenseException) [reply tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php]: It is not part of the test.

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php (hunk 2 above)
[the remark this answers is not in the document]
Comment (SenseException) [reply tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php]: I agree. Messages like "null is given, 1 was expected" are the usual messages that are shown on failing assertions.

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php [hunk 4]
```diff
@@ -73,6 +78,41 @@ public function testWillFindSongsInPaginator() : void
...
+        $query = $this->_em->getRepository(GH7820Line::class)
+            ->createQueryBuilder('l')
+            ->orderBy('l.lineNumber', Criteria::ASC);
+
+        self::assertSame(
+            self::SONG,
+            array_map(static function (GH7820Line $line) : string {
+                return $line->toString();
+            }, iterator_to_array(new Paginator($query))),
+            'Paginator runs again, SQL parameters are translated again, even with cached DQL -> SQL translation'
```
Comment (SenseException) [inline tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php]: Same as mentioned for the assert-message above.

**Review by SenseException — DISMISSED** [review]

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php (hunk 1 above)
Comment (ostrolucky) [reply tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php]: After another look, I can confirm this is neeed. Otherwise removing the fix would cause failure on first assertion

**Comment by ostrolucky** [comment]
I have taken liberty to improve these messages. Let me know if it's ok now

**Review by lcobucci — APPROVED** [review]
