### PR TITLE
Avoid triggering a deprecation notice in doctrine/collections

### LINKED ISSUE #12237: OneToManyPersister trigger deprecation.
### Bug Report

With commit doctrine/collections#472, the `OneToManyPersister` class trigger deprecations.

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 3.5.2

#### Summary

The `OneToManyPersister` class use `Criteria` class without setting the `$accessRawFieldValues` parameter value to `true`.

#### Current behavior

In the `count()` function, a `Criteria` class is created without the `$accessRawFieldValues` parameter:

```php
public function count(PersistentCollection $collection): int
{
    //...
    $criteria = new Criteria(Criteria::expr()->eq($mapping->mappedBy, $collection->getOwner()));
    //...
}
```
This is the same for the `containsKey()` and `contains()` functions.

#### Expected behavior

No deprecation must be raised.

```php
public function count(PersistentCollection $collection): int
{
    //...
    $criteria = new Criteria(
        expression: Criteria::expr()->eq($mapping->mappedBy, $collection->getOwner()),
        accessRawFieldValues: true
     );
    //...
}
```
Or use:

```php
Criteria::create(true);
```

#### How to reproduce

Just use a collection in an entity and call `count()` function.

### PR DESCRIPTION
**Pull request by mpdude**
This updates the code to avoid triggering the deprecation introduced in https://github.com/doctrine/collections/pull/472.

Closes #12237.

### CODE REVIEW

**Comment by mpdude** [comment]
@greg0ire Please advise: Should I bump requirements for doctrine/collections in composer.json here?

I guess I cannot, since we're still compatible with `^1.5 || ^2.1`, and I cannot drop 1.x support?

**Comment by greg0ire** [comment]
That's right, you shouldn't. Not in a patch release anyway.

**Comment by mpdude** [comment]
Found https://github.com/doctrine/doctrine-website/pull/485. I knew we discussed that before.

So, how to make PHPStan happy when I cannot tell for sure if checking against doctrine/collections >= 2.4.0 or below that?

**Comment by greg0ire** [comment]
What do you mean?

The CI job is installing `doctrine/collections` 2.4.0: https://github.com/doctrine/orm/actions/runs/18824547984/job/53705136455?pr=12238#step:6:102

File: src/Persisters/Collection/OneToManyPersister.php [hunk 1]
```diff
@@ -103,7 +103,8 @@ public function count(PersistentCollection $collection)
         // only works with single id identifier entities. Will throw an
         // exception in Entity Persisters if that is not the case for the
         // 'mappedBy' field.
-        $criteria = new Criteria(Criteria::expr()->eq($mapping['mappedBy'], $collection->getOwner()));
+        // @phpstan-ignore arguments.count
```
Comment (greg0ire) [inline src/Persisters/Collection/OneToManyPersister.php]: Why are you adding this?

Comment (mpdude) [reply src/Persisters/Collection/OneToManyPersister.php]: Here we have doctrine/collections 1.8.0 and PHPStan is complaining.

https://github.com/doctrine/orm/actions/runs/18839410187/job/53747881169?pr=12238

I was trying to get rid of those errors – but then it's a problem when it's the other way round and the argument is available (so the suppression is an error).

**Review by greg0ire — APPROVED** [review]

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @mpdude !
