### PR TITLE
 Don't presume one-to-one lookup returned an entity 

### LINKED ISSUE #9027: PHP error thrown if a one-to-one relationship cannot be retrieved
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | Sorry, I don't know what this means
| Version     | 2.9.3

#### Summary

PHP error thrown if a one-to-one relationship cannot be retrieved.

I can't profess to understand this too much, but it has come up in live system due to a combination of Doctrine, JMSSerializer and the SoftDeleteable filter from doctrine-extensions. I've managed to narrow it down to the following:

#### Current behavior

When `UnitOfWork->createEntity` is called, it fetches related records to make them part of the object returned. For bidirectional one-to-one relationships, in certain circumstances, it uses `EntityManager->find` to do this, then calls `spl_object_hash()` and `ReflectionProperty->setValue()` with the result.

If `find` doesn't find an object then it will return `null`, which is an invalid argument to both of those functions. Hence one of the following errors occurs:

```
spl_object_hash(): Argument #1 ($object) must be of type object, null given
```

```
Exception: [ReflectionProperty::setValue(): Argument #1 ($objectOrValue) must be of type object, null given]
```

(The first error is what happens when I recreate locally, the second is what we saw on our live system. This has only started happening since upgrading to PHP 8.)

I believe the result of `Entitymanager->find` needs to be checked to ensure it is an object.

#### How to reproduce

See #9028 for a failing test case and suggested fix.

```php
/** @Entity */
class Customer
{
    /**
     * One Customer has One Cart.
     * @OneToOne(targetEntity="Cart", mappedBy="customer")
     */
    private $cart;
}

/** @Entity */
class Cart
{
    /**
     * One Cart has One Customer.
     * @OneToOne(targetEntity="Customer", inversedBy="cart")
     * @JoinColumn(name="customer_id", referencedColumnName="id")
     */
    private $customer;
}

$uow = new UnitOfWork($this->_em);
$hints = ['fetchMode' => [Cart::class => ['customer' => ClassMetadata::FETCH_EAGER]]];
$cart = $uow->createEntity(Cart::class, ['id' => 1, 'customer' => 24252], $hints);

$this->assertEquals(null, $cart->customer);
```

This throws:
> spl_object_hash(): Argument #1 ($object) must be of type object, null given

#### Expected behavior

The error shouldn't throw and `$cart->customer` should be null.

### PR DESCRIPTION
**Pull request by gregtyler**
If `$this->em->find()` returns null, don't treat it like an object. Instead, just set the field to null and back out of the switch statement.

Includes a was-failing-but-now-passing test case.

Fixes #9027

### CODE REVIEW

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH9027Test.php [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+
+        try {
+            $this->_schemaTool->createSchema(
+                [
+                    $this->_em->getClassMetadata(GH9027Customer::class),
+                    $this->_em->getClassMetadata(GH9027Cart::class),
+                ]
+            );
+        } catch (Exception $e) {
+        }
```
Comment (greg0ire) [inline tests/Doctrine/Tests/ORM/Functional/Ticket/GH9027Test.php]: Can you please use something similar to what was done in https://github.com/doctrine/orm/pull/8962 ?

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH9027Test.php [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+    }
+
+    /**
+     * @group GH-9027
+     */
+    public function testUnitOfWorkHandlesNullRelations(): void
+    {
+        $uow = new UnitOfWork($this->_em);
+        $hints = ['fetchMode' => [GH9027Cart::class => ['customer' => ClassMetadata::FETCH_EAGER]]];
+        $cart = $uow->createEntity(GH9027Cart::class, ['id' => 1, 'customer' => 24252], $hints);
```
Comment (greg0ire) [inline tests/Doctrine/Tests/ORM/Functional/Ticket/GH9027Test.php]:
```suggestion
        $cart = $uow->createEntity(
                GH9027Cart::class,
                ['id' => 1, 'customer' => 24252],
                ['fetchMode' => [GH9027Cart::class => [
                        'customer' => ClassMetadata::FETCH_EAGER
                ]]];
        );
```

**Comment by greg0ire** [comment]
`vendor/bin/phpcbf` can help with the cs issues

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH9027Test.php (hunk 1 above)
Comment (gregtyler) [reply tests/Doctrine/Tests/ORM/Functional/Ticket/GH9027Test.php]: Done, sorry for using an old test as a template 🤦🏽

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH9027Test.php (hunk 2 above)
Comment (gregtyler) [reply tests/Doctrine/Tests/ORM/Functional/Ticket/GH9027Test.php]: I would've preferred this too, but `$hints` needs to be passed by reference, not value.

**Comment by gregtyler** [comment]
@greg0ire Thanks, I've fixed the issues I could :) Let me know if there's anything else I need to do!

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH9027Test.php (hunk 1 above)
Comment (greg0ire) [reply tests/Doctrine/Tests/ORM/Functional/Ticket/GH9027Test.php]: No worries, really, I would have done the same :)

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH9027Test.php (hunk 2 above)
Comment (greg0ire) [reply tests/Doctrine/Tests/ORM/Functional/Ticket/GH9027Test.php]: O_o OK

**Review by greg0ire — APPROVED** [review]

**Comment by bendavies** [comment]
well this is due to
https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/src/SoftDeleteable/Filter/SoftDeleteableFilter.php filtering out the select query on the FK row.

and you are working around https://github.com/doctrine-extensions/DoctrineExtensions/pull/745

if the FK exists in your row, we know an fk row exists so it seems fine for the ORM to assume the data will never be null. 
i'm unsure if this fix is correct because to me, it's working around a design problem with the soft delete behavior.

**Comment by gregtyler** [comment]
@bendavies Whilst the problem comes from SoftDeleteable in my instance, I figure we're _really_ working around a problem with Doctrine ORM Filters in general.

If I hydrate an object through `createEntity` and I have a filter which excludes an associated entity, Doctrine has to either:

1. Apply the filter and not add the associated entity
2. Ignore the filter and add the associated entity anyway
3. Throw an exception

As I understand it, Doctrine ORM's current behaviour is the first option, but it fails in PHP8 because of then mishandling the outcome if the entity is filtered out. I don't know if that's the *best* behaviour (I agree it's a silly situation to be in), but with this patch I'm just trying to keep it consistent across PHP versions.

**Review by SenseException — APPROVED** [review]
