### PR TITLE
Fix change set computation with enums

### LINKED ISSUE #10071: Fetched Entity with native Enum field with non empty changeSet (Enum <=> string)
### Bug Report

```php
// Order.php
    #[Column(type: Types::STRING, nullable: false, enumType: OrderStatus::class, options: ['charset' => 'utf8', 'collation' => 'utf8_unicode_ci'])]
    private OrderStatus $orderStatus;


// code.
$order = new Order();
$em->flush();
$em->clear();

$freshOrder = $em->createQueryBuilder()->select('o')->from(Order::class, 'o')->setMaxResults(1)->getQuery()->getSingleResult();

$uow->computeChangeSets();
$em->getUnitOfWork()->isScheduledForDelete($order); // returns true.
```

(The freshEneity is scheduled for the update because in the changeSet is 'strinngValue' of Enum::Foo.

But when I get the Entity like this

```php
$freshEntity = $this->getEntityManager()->find(Order::class, $orderId);
$uow->computeChangeSets();
$em->getUnitOfWork()->isScheduledForUpdate($order); // returns false, there is no update on fresh Entity.
```

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.13.x-dev

#### Summary

The $freshEntity with native Enum field shouldn't scheduled for updated

the failing test case is here https://github.com/doctrine/orm/pull/10073

### PR DESCRIPTION
**Pull request by HypeMC**
Fixes #10071 , uses test cases from #10073 by @mzk

My attempt at solving the issue. The `ReflectionEnumProperty::getValue()` method returns the value of the enum, while some hydrators pass an enum object in the data set to the `UnitOfWork::$originalEntityData` array.

The `SimpleObjectHydrator` doesn't convert strings into enums, while the `ObjectHydrator` (or to be more precise the `AbstractHydrator::gatherRowData()` method) does. Even though this doesn't seem to be causing any issues, the inconsistency seems unintentional to me, so if you think it should be fixed please let me know and I'll open a PR.

### CODE REVIEW

**Comment by michnovka** [comment]
This is a good fix.

I think `SimpleObjectHydrator` should also convert strings into enums.

**Comment by HypeMC** [comment]
> This is a good fix.
> 
> I think `SimpleObjectHydrator` should also convert strings into enums.

See #10088

**Comment by michnovka** [comment]
@derrabus this is an important fix for enums, can we have it merged for the next 2.13 point release?

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you @HypeMC.

**Comment by mroeling** [comment]
Is there an e.t.a. on a new release with this fix please?

**Comment by greg0ire** [comment]
@mroeling we are waiting on #10088 to release this.

File: lib/Doctrine/ORM/UnitOfWork.php [hunk 1]
```diff
@@ -743,6 +744,10 @@ public function computeChangeSet(ClassMetadata $class, $entity)
 
                 $orgValue = $originalData[$propName];
 
+                if ($orgValue instanceof BackedEnum) {
+                    $orgValue = $orgValue->value;
+                }
+
                 // skip if value haven't changed
                 if ($orgValue === $actualValue) {
```
Comment (shadowhand) [inline lib/Doctrine/ORM/UnitOfWork.php:752]: This PR is broken, and I'm pretty sure this is why. Based on the changes in line 747, we probably also need to have:

```php
if ($actualValue instanceof BackedEnum) {
    $actualValue = $actualValue->value;
}
```

Comment (shadowhand) [reply lib/Doctrine/ORM/UnitOfWork.php:752]: https://github.com/doctrine/orm/issues/10249

Comment (michnovka) [reply lib/Doctrine/ORM/UnitOfWork.php:752]: I don think so. Check the code a bit above:

https://github.com/HypeMC/orm/blob/a1ed32f697f66d33de42fe96b1ea90e873ba2d5f/lib/Doctrine/ORM/UnitOfWork.php#L670

then 

https://github.com/HypeMC/orm/blob/a1ed32f697f66d33de42fe96b1ea90e873ba2d5f/lib/Doctrine/ORM/UnitOfWork.php#L699

So actual value is fetched through reflection. And if you check the `ReflectionEnumProperty::getValue()`

https://github.com/HypeMC/orm/blob/a1ed32f697f66d33de42fe96b1ea90e873ba2d5f/lib/Doctrine/ORM/Mapping/ReflectionEnumProperty.php#L36-L63

It returns the `$enum->value` already. Therefore your proposed 

```php
if ($actualValue instanceof BackedEnum) {
    $actualValue = $actualValue->value;
}
```

seems redundant.

Comment (shadowhand) [reply lib/Doctrine/ORM/UnitOfWork.php:752]: I could be wrong. All I know is that this patch broke several of our entities that use enums, and that seemed like a possibility. I haven't tested the theory.
