### PR TITLE
fix: handle repeatable attributes

### LINKED ISSUE #8755: bug: AttributeDriver throws error for repeatable attributes
[`Doctrine\ORM\Mapping\Driver\AttributeDriver`](https://github.com/doctrine/orm/blob/2.9.x/lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php) extends [`Doctrine\Persistence\Mapping\Driver\AnnotationDriver`](https://github.com/doctrine/persistence/blob/2.2.x/lib/Doctrine/Persistence/Mapping/Driver/AnnotationDriver.php).

`AttributeDriver::isTransient` resolves to `AnnotationDriver::isTransient`.

If a class has repeating attributes an error is thrown in [AnnotationDriver:182](https://github.com/doctrine/persistence/blob/79e97bcb1dfe3b242961253d81b8357a04e96ca1/lib/Doctrine/Persistence/Mapping/Driver/AnnotationDriver.php#L179-L182) because `$annot` is an `array`.

```php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

#[ORM\Index(columns: ['foo'])]
#[ORM\Index(columns: ['bar', 'baz'])]
#[ORM\Entity]
class Foo
{
 //...
```

Workaround: When the repeatable attributes trail non-repeatable ones of `entityAnnotationClasses` the method returns before the error occurs.

### PR DESCRIPTION
**Pull request by ph-fritsche**
Introduces `isTransient` on `AttributeDriver` for better handling of repeatable attributes. Cleans up `AttributeReader` API a little.

Closes #8755

### CODE REVIEW

File: lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php [hunk 1]
```diff
@@ -38,6 +40,23 @@ public function __construct(array $paths)
...
 
+    /**
+     * {@inheritDoc}
+     */
+    public function isTransient($className)
+    {
+        $classAnnotations = $this->reader->getClassAnnotations(new ReflectionClass($className));
+
+        foreach ($classAnnotations as $a) {
+            $annot = is_array($a) ? $a[0] : $a;
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php]: @ph-fritsche can `$a` really be an array?

Comment (ph-fritsche) [reply lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php]:
```php
            $annot = /* is_array($a) ? $a[0] : */ $a;
```
results in `phpunit` reporting:
```
There was 1 error:

1) Doctrine\Tests\ORM\Mapping\AttributeDriverTest::testIsTransientWithRepeatableAttributes
TypeError: get_class(): Argument #1 ($object) must be of type object, array given

/workspaces/misc/doctrine-orm/lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php:52
/workspaces/misc/doctrine-orm/tests/Doctrine/Tests/ORM/Mapping/AttributeDriverTest.php:85
```
due to:
https://github.com/doctrine/orm/blob/332c314e9f055d729555f2861fcb81ee50e482b5/lib/Doctrine/ORM/Mapping/Driver/AttributeReader.php#L26-L28
https://github.com/doctrine/orm/blob/332c314e9f055d729555f2861fcb81ee50e482b5/lib/Doctrine/ORM/Mapping/Driver/AttributeReader.php#L66-L85

Comment (greg0ire) [reply lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php]: Indeed. The phpdoc of `convertToAttributeInstances` is wrong, this is why the build fails.

Comment (greg0ire) [reply lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php]: Also, the phpdoc of `Doctrine\Common\Annotations\Reader` is wrong, and that's in another package :grimacing:

Comment (greg0ire) [reply lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php]: Or rather `AttributeReader` does not implement the interface it says it implements. Widening the return type in the interface wouldn't be a BC break for classes implementing it, but it would be a BC break for calling code. Not sure what the best course of action would be here @beberlei . I think we should widen it in `doctrine/annotations`, but to be clean, that would require a major release :grimacing: or since it's just phpdoc, we pray it does not break to many static analysis builds and release it as a minor?

Comment (ph-fritsche) [reply lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php]: Maybe `Doctrine\ORM\AttributeDriver` should not extend `Doctrine\Persistence\Mapping\Driver\AnnotationDriver` at all.
How about we internally refactor `Doctrine\Persistence\Mapping\Driver\AnnotationDriver::getAllClassNames` into another class that could be reused by `Doctrine\ORM\AttributeDriver`?
This way `doctrine/persistence` and `doctrine/annotation` would not have any breaking changes.

If you want to be sentimental about the version increment on this package, one could argue that the declaration of `Doctrine\ORM\AttributeDriver` was broken from the beginning in `2.9` so breaking that inheritance here might be released as a fix.

Comment (beberlei) [reply lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php]: That is a course of action we could take for the next minor release. To fix this bug the small solution plus suppression of tooling errors is my preference.

Comment (greg0ire) [reply lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php]: I just thought of another quite simple solution that does not imply changing other packages: let's use an iterable object instead of an array to represent a bug of attributes. As a bonus it will make the code clearer and will answer `can $a really be an array?` because you will have `$a instanceof RepeatableAttributeCollection` instead of `is_array($a)`. WDYT?

Comment (greg0ire) [reply lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php]: Here is what it would look like: https://github.com/ph-fritsche/doctrine-orm/pull/1

**Comment by beberlei** [comment]
Can you exclude AttributeReader from php-stan and psalm analysis for now? We should upgrade to check with 8.0 in 2.10 branch.

**Comment by beberlei** [comment]
@ph-fritsche just thought the ping pong fixing some config changes might going to be tedious and made the change myself for now. Lets see what the CI says about this.

**Review by beberlei — DISMISSED** [review]
This is good for now to fix the error.

I would say we could improve this in the future (2.10) by changing `AttributeReader` to have only three functions `getAnnotations() : array<Annotation>`, `getFilteredAnnotations(string $className) : array<Annotation>` and `getAnnotation(string $className) : Annotation` which throws when the class name is repeatable.

File: tests/Doctrine/Tests/ORM/Mapping/AttributeDriverTest.php [hunk 2]
```diff
@@ -78,6 +78,13 @@ public function testOriginallyNestedAttributesDeclaredWithoutOriginalParent(): v
         );
         $this->assertEquals(['assoz_id', 'assoz_id'], $metadata->associationMappings['assoc']['joinTableColumns']);
     }
+
+    public function testIsTransientWithRepeatableAttributes(): void
+    {
+        $driver      = $this->loadDriver();
+        $isTransient = $driver->isTransient(AttributeEntityStartingWithRepeatableAttributes::class);
+        $this->assertFalse($isTransient);
+    }
```
Comment (SenseException) [inline tests/Doctrine/Tests/ORM/Mapping/AttributeDriverTest.php]: Covering the `true` case too would be nice.

**Review by SenseException — CHANGES_REQUESTED** [review]

**Review by beberlei — APPROVED** [review]
