### PR TITLE
[GH-7505] Bug in SimpleObjectHydrator when using inheritance with same field

### LINKED ISSUE #7505: Hydratation error when two classes with the same parent class both define the same property with different types.
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.3

#### Summary

`SimpleObjectHydrator` produces a type error when two classes with the same parent class both define a property with the same name and different types.

I think this may be related to issue #5989.

#### Current behavior

When two classes inherit from the same parent using `SINGLE_TABLE` inheritance, and both classes define the same property with different types, `SimpleObjectHydrator` produce a type error if one of the properties is of type `simple_array`.

#### How to reproduce

Create an abstract class with two child classes:
```php
use Doctrine\ORM\Annotation as ORM;

/**
 * @ORM\Entity()
 * @ORM\Table(name="test_responses")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({
 *     "array"       = ArrayResponse::class,
 *     "text"        = TextResponse::class,
 * })
 */
abstract class AbstractResponse {
    /**
     * @ORM\Id @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    public $id;
}
```

Create two child classes. Each class defines the same property with different types.
The first class use the type `simple_array` and the second class has a `string` property :
```php
/**
 * @ORM\Entity()
 */
class ArrayResponse extends AbstractResponse {
    /**
     * @ORM\Column(name="value_array", type="simple_array")
     *
     * @var array
     */
    public $value = [];
}

/**
 * @ORM\Entity()
 */
class TextResponse extends AbstractResponse {
    /**
     * @ORM\Column(name="value_string", type="string")
     *
     * @var string|null
     */
    public $value = null;
}
```

Create an instance of the second class and flush the `EntityManager`:
```php
$textResponse = new TextResponse();
$em->persist($textResponse);
$em->flush();
```

Clear the `EntityManager` and fetch the instance:
```php
$em->clear();

/** @var TextResponse $arrayResponse */
$textResponse = $em->getRepository(AbstractResponse::class)
                   ->find($textResponse->id);

var_dump($textResponse->value); // Display an empty array (type error)
```

#### Expected behavior

The value of `$textResponse->value` should be NULL, because the property `$value` of class `TextResponse` has type `string|null`.

### PR DESCRIPTION
**Pull request by beberlei**
Fixes #7505 

Supersedes https://github.com/doctrine/orm/pull/7506

### CODE REVIEW

**Review by SenseException — DISMISSED** [review]

File: lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php [hunk 1]
```diff
@@ -134,6 +136,11 @@ protected function hydrateRowData(array $sqlResult, array &$result)
 
             // Prevent overwrite in case of inherit classes using same property name (See AbstractHydrator)
             if ( ! isset($data[$fieldName]) || ! $valueIsNull) {
+                // If we have inheritance in resultset, make sure the field belongs to the correct class
+                if (isset($cacheKeyInfo['discriminatorValues']) && ! in_array($discrColumnValue, $cacheKeyInfo['discriminatorValues'], true)) {
```
Comment (lcobucci) [inline lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php]: Would it be possible to combine this with the previous if statement? It would simplify things, wouldn't it?

**Review by lcobucci — CHANGES_REQUESTED** [review]
Fix LGTM, just a few nitpicks... 

The original issue also mention ensuring that the schema validation detects an issue when the column name is the same, do we have tests for this scenario?

About joined tables, does it behaves the same way? Could we also cover it with tests?

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH7505Test.php [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+        $this->setUpEntitySchema([
+            GH7505AbstractResponse::class,
+            GH7505ArrayResponse::class,
+            GH7505TextResponse::class,
+        ]);
+    }
+
+    public function testSimpleArrayTypeHydratedCorrectly() : void
+    {
+        $arrayResponse = new GH7505ArrayResponse();
```
[the remark this answers is not in the document]
Comment (beberlei) [reply tests/Doctrine/Tests/ORM/Functional/Ticket/GH7505Test.php]: Not sure it matters, the entity is needed for the test-case

File: lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php (hunk 1 above)
Comment (beberlei) [reply lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php]: No its not possible.

**Comment by beberlei** [comment]
@lcobucci Joined tables behave the same, this code is unaware of type of inheritance. The schema validator should not make it an issue if its the same column name, because that is supported behavior as per the code.
