### PR TITLE
ScalarColumnHydrator: prevent early-bail on falsy values

### LINKED ISSUE #9230: Single column hydration returns nothing if first item is false-like
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10.3 

#### Summary

While working on my open source app I found out that scalar column hydration does not return any value, just empty array, when first element of the results is false-like (null, 0, ''…). 

#### How to reproduce

Do something like this but without `<> NULL` and `<> ''`: https://github.com/TomaszGasior/RadioLista-v3/blob/8a2b4fa0d6d9fb85d83a36a00bd61d2031a1a8b3/src/Repository/RadioStationRepository.php#L68

Simplified example:

```php
return $this->createQueryBuilder('radioStation')
    ->select('DISTINCT radioStation.'.$column)
    ->getQuery()
    ->getSingleColumnResult()
;
```

If first item from result set is false-like, empty array is returned.

#### Expected behavior

I would like to get all values from the column, even something like null, ''.

Adding `false !==` to https://github.com/doctrine/orm/blob/6414ad4cbb898e4ae027a1a0de48b31984002dea/lib/Doctrine/ORM/Internal/Hydration/ScalarColumnHydrator.php#L31 kinda fixes the issue. I don't know whether Doctrine is able to return native `false` for DBMS-es supporting it and how to support that case if it's needed.

### PR DESCRIPTION
**Pull request by MrMitch**
Hi !

This is my first contribution to Doctrine, please let me know if there is anything I can do to facilitate the review process.

--

Fix #9230

Falsy values stop the hydration process in `$query->getSingleColumnResult()`. If the array of values fetched from the database contains a value that is "falsy", every value after that value and including that value is missing from the array that is returned.

This is because of the way the database values are retreived in ScalarColumnHydrator : https://github.com/doctrine/orm/blob/f4d5283f705f6ac51e81c8299ace074a619b40d7/lib/Doctrine/ORM/Internal/Hydration/ScalarColumnHydrator.php#L31-L33

This PR fixes that by fetching all the values and returning them as is. As before, and to keep things consistent with the previous behavior of both ScalarHydrator and ScalarColumnHydrator, no type conversion is done between the database value and the PHP value. According to a comment in `AbstractHydrator`, this is the expected behavior for scalar hydrators that is a legacy behavior from 2.0 : https://github.com/doctrine/orm/blob/f4d5283f705f6ac51e81c8299ace074a619b40d7/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php#L498-L505

### CODE REVIEW

File: tests/Doctrine/Tests/Models/ReadonlyProperties/Book.php [hunk 1]
```diff
@@ -5,7 +5,6 @@
 namespace Doctrine\Tests\Models\ReadonlyProperties;
 
 use Doctrine\Common\Collections\ArrayCollection;
-use Doctrine\Common\Collections\Collection;
```
Comment (MrMitch) [inline tests/Doctrine/Tests/Models/ReadonlyProperties/Book.php]: This as been automatically fixed by `vendor/bin/phpcbf` (and flagged by `vendor/bon/phpcs`). The original error was not related to this PR and was present before any changes were made.

```
# vendor/bin/phpcs 
.....................................E...................... 60 / 76 (79%)
................                                             76 / 76 (100%)



FILE: tests/Doctrine/Tests/Models/ReadonlyProperties/Book.php
--------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------
 8 | ERROR | [x] Type Doctrine\Common\Collections\Collection is not used in this file.
   |       |     (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)
--------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------------

Time: 998ms; Memory: 174MB
```

```
# vendor/bin/phpcbf 
.................F.......................................... 60 / 76 (79%)
................                                             76 / 76 (100%)



PHPCBF RESULT SUMMARY
----------------------------------------------------------------------------
FILE                                                        FIXED  REMAINING
----------------------------------------------------------------------------
tests/Doctrine/Tests/Models/ReadonlyProperties/Book.php     1      0
----------------------------------------------------------------------------
A TOTAL OF 1 ERROR WERE FIXED IN 1 FILE
----------------------------------------------------------------------------

Time: 12,03 secs; Memory: 10MB
```



I'm happy to reverse if this is outside of the scope of this PR.

**Comment by derrabus** [comment]
Your patch introduces some complexity to the codebase by duplicating logic from the DBAL. Naive question: Shouldn't your problem be fixed if you changed the loop this way?

```diff
-         while ($row = $this->statement()->fetchOne()) {
+         foreach ($this->statement()->iterateColumn() as $row) {
```

File: tests/Doctrine/Tests/Models/ReadonlyProperties/Book.php (hunk 1 above)
Comment (derrabus) [reply tests/Doctrine/Tests/Models/ReadonlyProperties/Book.php]: Yes, please revert. And please use PHP 8.1 to execute PHPCS.

Comment (MrMitch) [reply tests/Doctrine/Tests/Models/ReadonlyProperties/Book.php]: @derrabus reverted, thanks !

**Comment by MrMitch** [comment]
@derrabus Thank you for your quick reply. You're absolutely right, using a simple foreach loop produces the same result and reduces the complexity, I've amended the code accordingly.

We could even further reduce the length of the method by using `return iterator_to_array($this->statement()->iterateColumn())`, but I'm not sure that would add real value or maintainability.

**Comment by MrMitch** [comment]
@derrabus I've amended the code further to fix support for databases that have native support for `boolean` values (like PostgreSQL).

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you, @MrMitch!

**Comment by MrMitch** [comment]
Happy to contribute, thank you for reviewing this with care.
