### PR TITLE
Make proxyDir and proxyNs nullable and optional

### LINKED ISSUE #11997: [3.4.0] TypeError from ProxyFactory::__construct() when using native lazy objects
### Bug Report

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 3.4.0
| PHP                                     | 8.4.8

#### Summary

When using the new native lazy objects, I get an TypeError in the EntityManager constructor, when it tries to create a ProxyFactory. $proxyDir and $proxyNs need to be strings, but because those are not set, nulls are given.

My workaround is to set empty strings:

```php
$config->enableNativeLazyObjects(true);
$config->setProxyDir('');
$config->setProxyNamespace('');
```

PHP Version: 8.4.8

Stack Trace:

```
TypeError thrown with message "Doctrine\ORM\Proxy\ProxyFactory::__construct(): Argument #2 ($proxyDir) must be of type string, null given, called in /app/vendor/doctrine/orm/src/EntityManager.php on line 137"

Stacktrace:
#3 TypeError in /app/vendor/doctrine/orm/src/Proxy/ProxyFactory.php:144
#2 Doctrine\ORM\Proxy\ProxyFactory:__construct in /app/vendor/doctrine/orm/src/EntityManager.php:137
#1 Doctrine\ORM\EntityManager:__construct in /app/src/Helpers/Database/Database.php:47
#0 Enterprise\Helpers\Database\Database:init in /app/public/index.php:44
```

### PR DESCRIPTION
**Pull request by greg0ire**
When using native lazy objects, it should be possible to omit these arguments, hence the default value.
Also, when using native lazy objects, one should not have to configure the corresponding Configuration attributes, which means EntityManager__construct() should be able to pass null to this class, hence the nullability.

Fixes #11997

### CODE REVIEW

File: tests/Tests/ORM/Proxy/ProxyFactoryTest.php [hunk 1]
```diff
@@ -209,6 +211,18 @@ public function testProxyClonesParentFields(): void
         self::assertSame(1000, $cloned->getSalary(), 'Expect properties on the CompanyEmployee class to be cloned');
         self::assertSame('Bob', $cloned->getName(), 'Expect properties on the CompanyPerson class to be cloned');
     }
+
+    #[RequiresPhp('8.4')]
+    #[DoesNotPerformAssertions]
+    public function testProxyFactoryAcceptsNullProxyArgsWhenNativeLazyObjectsAreEnabled(): void
```
Comment (SenseException) [inline tests/Tests/ORM/Proxy/ProxyFactoryTest.php:216]: I'd rather see a proxy created by the ProxyFactory than having this test without assertions.

**Review by SenseException — CHANGES_REQUESTED** [review]

**Review by SenseException — APPROVED** [review]
