### PR TITLE
Fix using enums with the QueryBuilder

### LINKED ISSUE #10057: 2.13.2 breaks all queries with object hydration for entities using Enum fields
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.13.2

#### Summary

[This change](https://github.com/doctrine/orm/pull/10041/files#diff-f1936bc3177c94ebd06906a54a439e496b410cfee881d6740ac344f03382e0ddR468) in #10041 breaks all queries with object hydration for entities with an Enum field.

#### Previous behavior

It worked.

#### Current behavior

Exception with stack trace:

```
TypeError:
App\Domain\Channel\ChannelId::from(): Argument #1 ($value) must be of type string, App\Domain\Channel\ChannelId given

  at vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ReflectionEnumProperty.php:93
  at App\Domain\Channel\ChannelId::from()
     (vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ReflectionEnumProperty.php:93)
  at Doctrine\ORM\Mapping\ReflectionEnumProperty->initializeEnumValue()
     (vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ReflectionEnumProperty.php:77)
  at Doctrine\ORM\Mapping\ReflectionEnumProperty->setValue()
     (vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2745)
  at Doctrine\ORM\UnitOfWork->createEntity()
     (vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php:266)
  at Doctrine\ORM\Internal\Hydration\ObjectHydrator->getEntity()
     (vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php:492)
  at Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateRowData()
     (vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php:148)
  at Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateAllData()
     (vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php:270)
  at Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll()
     (vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:1224)
  at Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache()
     (vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:1165)
  at Doctrine\ORM\AbstractQuery->execute()
     (vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:953)
  at Doctrine\ORM\AbstractQuery->getOneOrNullResult()
     (src/Infrastructure/Doctrine/ORM/Repository/OrderRepository.php:51)
  at App\Infrastructure\Doctrine\ORM\Repository\OrderRepository->get()
     (src/Infrastructure/Symfony/Controller/Account/OrderDetailAction.php:43)
  at App\Infrastructure\Symfony\Controller\Account\OrderDetailAction->__invoke()
     (vendor/symfony/http-kernel/HttpKernel.php:153)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:75)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/srv/share/vendor/autoload_runtime.php')
     (public/index.php:7)   
```

#### How to reproduce

I have an `Order` entity with a `ChannelId` field that looks like this (simplified):

```
/** @final */
#[ORM\Entity]
#[ORM\Table(name: '`order`')]
class Order
{
    /** @psalm-immutable */
    #[ORM\Id]
    #[ORM\Column(type: 'order_id')]
    private OrderId $id

    /** @psalm-immutable */
    #[ORM\Column(type: 'string', enumType: ChannelId::class)]
    private ChannelId $channelId;
}
```

And a repository (simplified) with this method:

```
/** @throws OrderWithIdDoesNotExist */
public function get(OrderId $orderId): Order
{
    $manager = $this->registry->getManagerForClass(Order::class);
    $repository = $manager->getRepository(Order::class);
        
    $queryBuilder = $repository->createQueryBuilder('o');
    $queryBuilder->where('o.id = :id');
    $queryBuilder->setParameter('id', $orderId->toString());

    $order = $queryBuilder->getQuery()->getOneOrNullResult();

    if (! $order instanceof Order) {
        throw new OrderWithIdDoesNotExist($orderId);
    }

    return $order;
}
```

I'll see if I can come up with reproducing test case.

### PR DESCRIPTION
**Pull request by HypeMC**
Fixes #10057.

After upgrading to version `2.13.2` I started getting the following error:

```
App\Enum\TestEnum::from(): Argument #1 ($value) must be of type string, App\Enum\TestEnum given
```

It happens when an enum is used with the `QueryBuilder`, eg:

```php
$testRepository
    ->createQueryBuilder('t')
    ->where('t.enum = :type')
    ->setParameter('type', TestEnum::Foo)
    ->getQuery()->getResult()
;
```

Caused by #10041.

Since my knowledge of the ORM code base is limited I'm not sure if this is the best place to fix the bug, so any suggestions are appreciated.

### CODE REVIEW

File: lib/Doctrine/ORM/Mapping/ReflectionEnumProperty.php [hunk 1]
```diff
@@ -63,12 +63,12 @@ public function getValue($object = null)
...
     /**
-     * @param object                         $object
-     * @param int|string|int[]|string[]|null $value
+     * @param object                                    $object
+     * @param int|string|int[]|string[]|BackedEnum|null $value
      */
     public function setValue($object, $value = null): void
     {
-        if ($value !== null) {
+        if ($value !== null && ! $value instanceof BackedEnum) {
```
Comment (janatjak) [inline lib/Doctrine/ORM/Mapping/ReflectionEnumProperty.php]:
```php
/**
 * @param object     $object
 * @param int|string|BackedEnum $value
 */
private function initializeEnumValue($object, $value): BackedEnum
{
    if ($value instanceof BackedEnum) {
        return $value;
    }

    $enumType = $this->enumType;
    ...
```

Comment (HypeMC) [reply lib/Doctrine/ORM/Mapping/ReflectionEnumProperty.php]: Good point, `$value` can be an array of enums, fixed.

**Comment by greg0ire** [comment]
Cc @michnovka

**Review by derrabus — APPROVED** [review]

**Review by janatjak — APPROVED** [review]

**Comment by michnovka** [comment]
Ill review this on Sunday and check how my PR caused this issue and confirm
this is a good fix. thx for waiting

**Comment by michnovka** [comment]
This is a good fix, and I also believe we now cover all enum hydrator test cases, so no such regression bugs should occur in the future. Thanks @HypeMC

**Comment by greg0ire** [comment]
Thanks @HypeMC !

**Comment by tip2tail** [comment]
Hello, when can we expect this to be released?

**Comment by greg0ire** [comment]
Soon :tm: 

I think we should try to batch #10059  in the same release, and it looks ready.

**Comment by trsteel88** [comment]
There is a further issue here. hasChangedField is always returning true for an enum regardless of whether it actually changed.

When using hasChangedField('status') it shows it as changed when it hasn't.

**Comment by trsteel88** [comment]
Just further to my last comment, when dumping the old/new values. The difference is that getOldValue() gives the enum object whereas getNewValue() return the enum's value. My guess is the comparison is failing because these should both be the enum object?

**Comment by michnovka** [comment]
@trsteel88 there is a separate PR for this issue https://github.com/doctrine/orm/pull/10074
