### PR TITLE
FIX - nested dto's doesn't have arguments in good order and Dto with only objects bug

### LINKED ISSUE #11824: [BUG] - nested object argument are not in asked order
### Bug Report

there is a bug in nested dto's,

In arguments, the dto's come in last in argument lists after scalar values,  and not in the asked order.

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 3.3.0

This test currently fails : 

```php
   public function testShouldSupportNestedNewOperatorsWithDtoFirst(): void
    {
        $dql = '
            SELECT
                new CmsUserDTO(
                    u.name,
                    e.email,
                    new CmsAddressDTO(
                        a.country,
                        a.city,
                        a.zip,
                        new CmsAddressDTO(
                            a.country,
                            a.city,
                            a.zip
                        )
                    ),
                    555812452
                ) as user,
                u.status,
                u.username as cmsUserUsername
            FROM
                Doctrine\Tests\Models\CMS\CmsUser u
            JOIN
                u.email e
            JOIN
                u.address a
            ORDER BY
                u.name';

        $query  = $this->getEntityManager()->createQuery($dql);
        $result = $query->getResult();

        self::assertCount(3, $result);

        self::assertInstanceOf(CmsUserDTO::class, $result[0]['user']);
        self::assertInstanceOf(CmsUserDTO::class, $result[1]['user']);
        self::assertInstanceOf(CmsUserDTO::class, $result[2]['user']);

        self::assertInstanceOf(CmsAddressDTO::class, $result[0]['user']->address);
        self::assertInstanceOf(CmsAddressDTO::class, $result[1]['user']->address);
        self::assertInstanceOf(CmsAddressDTO::class, $result[2]['user']->address);

        self::assertSame($this->fixtures[0]->name, $result[0]['user']->name);
        self::assertSame($this->fixtures[1]->name, $result[1]['user']->name);
        self::assertSame($this->fixtures[2]->name, $result[2]['user']->name);

        self::assertSame($this->fixtures[0]->email->email, $result[0]['user']->email);
        self::assertSame($this->fixtures[1]->email->email, $result[1]['user']->email);
        self::assertSame($this->fixtures[2]->email->email, $result[2]['user']->email);

        self::assertSame($this->fixtures[0]->address->city, $result[0]['user']->address->city);
        self::assertSame($this->fixtures[1]->address->city, $result[1]['user']->address->city);
        self::assertSame($this->fixtures[2]->address->city, $result[2]['user']->address->city);

        self::assertSame($this->fixtures[0]->address->country, $result[0]['user']->address->country);
        self::assertSame($this->fixtures[1]->address->country, $result[1]['user']->address->country);
        self::assertSame($this->fixtures[2]->address->country, $result[2]['user']->address->country);

        self::assertSame('555812452', $result[0]['user']->phonenumbers);
        self::assertSame('555812452', $result[1]['user']->phonenumbers);
        self::assertSame('555812452', $result[2]['user']->phonenumbers);

        self::assertSame($this->fixtures[0]->status, $result[0]['status']);
        self::assertSame($this->fixtures[1]->status, $result[1]['status']);
        self::assertSame($this->fixtures[2]->status, $result[2]['status']);

        self::assertSame($this->fixtures[0]->username, $result[0]['cmsUserUsername']);
        self::assertSame($this->fixtures[1]->username, $result[1]['cmsUserUsername']);
        self::assertSame($this->fixtures[2]->username, $result[2]['cmsUserUsername']);
    }
```

### PR DESCRIPTION
**Pull request by eltharin**
for resolve https://github.com/doctrine/orm/issues/11824

add arguments sort for nested dto's contructors 

Working on another PR, I figure that when a Dto have only objects as arguments `newObjectMappings` was not filled so I move parent declaration in `newObject` (keeping BC)

### CODE REVIEW

File: tests/Tests/ORM/Functional/NewOperatorTest.php [hunk 1]
```diff
@@ -1087,6 +1167,68 @@ public function testShouldSupportNestedNewOperators(): void
         self::assertSame($this->fixtures[2]->username, $result[2]['cmsUserUsername']);
     }
 
+    public function testOnLyObjectInObject(): void
```
Comment (greg0ire) [inline tests/Tests/ORM/Functional/NewOperatorTest.php]:
```suggestion
    public function testOnlyObjectInObject(): void
```

File: src/Query/AST/NewObjectExpression.php [hunk 2]
```diff
@@ -18,8 +18,8 @@ public function __construct(public string $className, public array $args)
     {
     }
 
-    public function dispatch(SqlWalker $walker): string
+    public function dispatch(SqlWalker $walker, string|null $parentAlias = null): string
```
Comment (greg0ire) [inline src/Query/AST/NewObjectExpression.php]: This is a breaking change for extending classes, you should be using `func_get_args()` here.

Comment (eltharin) [reply src/Query/AST/NewObjectExpression.php]: ok.
Can I put it in 3.4.0 (in my next PR) ?

Comment (greg0ire) [reply src/Query/AST/NewObjectExpression.php]: :thinking: well no, it would mean the breaking change would land in the next 3.3 release, right?

File: src/Query/AST/NewObjectExpression.php [hunk 3]
```diff
@@ -18,8 +21,10 @@ public function __construct(public string $className, public array $args)
...
```
Comment (greg0ire) [inline src/Query/AST/NewObjectExpression.php]:
```suggestion
    public function dispatch(SqlWalker $walker /*, string|null $parentAlias = null */): string
```

File: src/Internal/Hydration/AbstractHydrator.php [hunk 4]
```diff
@@ -336,21 +346,20 @@ protected function gatherRowData(array $data, array &$id, array &$nonemptyCompon
...
-            if (! isset($rowData['newObjects'][$ownerIndex . ':' . $argIndex])) {
-                continue;
+        $nestedEntities = [];
+        foreach ($this->resultSetMapping()->nestedNewObjectArguments as ['ownerIndex' => $ownerIndex, 'argIndex' => $argIndex, 'argAlias' => $argAlias]) {
+            if (array_key_exists($argAlias, $rowData['newObjects'])) {
+                ksort($rowData['newObjects'][$argAlias]['args']);
+                $rowData['newObjects'][$ownerIndex]['args'][$argIndex] = $rowData['newObjects'][$argAlias]['class']->newInstanceArgs($rowData['newObjects'][$argAlias]['args']);
+                unset($rowData['newObjects'][$argAlias]);
+            } else {
+                throw new LogicException($argAlias . ' not exist');
```
Comment (greg0ire) [inline src/Internal/Hydration/AbstractHydrator.php]:
```suggestion
                throw new LogicException(sprintf("%s does not exist", $argAlias));
```

File: src/Internal/Hydration/AbstractHydrator.php [hunk 5]
```diff
@@ -336,21 +346,20 @@ protected function gatherRowData(array $data, array &$id, array &$nonemptyCompon
...
-            if (! isset($rowData['newObjects'][$ownerIndex . ':' . $argIndex])) {
-                continue;
+        $nestedEntities = [];
+        foreach ($this->resultSetMapping()->nestedNewObjectArguments as ['ownerIndex' => $ownerIndex, 'argIndex' => $argIndex, 'argAlias' => $argAlias]) {
+            if (array_key_exists($argAlias, $rowData['newObjects'])) {
+                ksort($rowData['newObjects'][$argAlias]['args']);
+                $rowData['newObjects'][$ownerIndex]['args'][$argIndex] = $rowData['newObjects'][$argAlias]['class']->newInstanceArgs($rowData['newObjects'][$argAlias]['args']);
+                unset($rowData['newObjects'][$argAlias]);
+            } else {
+                throw new LogicException(sprintf("%s does not exist", $argAlias);
```
Comment (greg0ire) [inline src/Internal/Hydration/AbstractHydrator.php]:
```suggestion
                throw new LogicException(sprintf("%s does not exist", $argAlias));
```

File: src/Query/ResultSetMapping.php [hunk 6]
```diff
@@ -159,6 +159,13 @@ class ResultSetMapping
      */
     public array $newObjectMappings = [];
 
+    /**
+     * Maps object Ids in the result set to classnames.
+     *
+     * @phpstan-var array<string|int, array<string, mixed>>
+     */
+    public array $newObject = [];
```
Comment (greg0ire) [inline src/Query/ResultSetMapping.php:167]: To be simplified

File: src/Query/ResultSetMapping.php [hunk 7]
```diff
@@ -159,6 +159,13 @@ class ResultSetMapping
      */
     public array $newObjectMappings = [];
 
+    /**
+     * Maps object Ids in the result set to classnames.
+     *
+     * @phpstan-var array<string|int, string>
```
Comment (greg0ire) [inline src/Query/ResultSetMapping.php]: If it's a `class-string`, let's say so?

```suggestion
     * @phpstan-var array<string|int, class-string>
```

File: src/Internal/Hydration/AbstractHydrator.php [hunk 8]
```diff
@@ -336,21 +346,20 @@ protected function gatherRowData(array $data, array &$id, array &$nonemptyCompon
...
-            if (! isset($rowData['newObjects'][$ownerIndex . ':' . $argIndex])) {
-                continue;
+        $nestedEntities = [];
+        foreach ($this->resultSetMapping()->nestedNewObjectArguments as ['ownerIndex' => $ownerIndex, 'argIndex' => $argIndex, 'argAlias' => $argAlias]) {
+            if (array_key_exists($argAlias, $rowData['newObjects'])) {
+                ksort($rowData['newObjects'][$argAlias]['args']);
+                $rowData['newObjects'][$ownerIndex]['args'][$argIndex] = $rowData['newObjects'][$argAlias]['class']->newInstanceArgs($rowData['newObjects'][$argAlias]['args']);
+                unset($rowData['newObjects'][$argAlias]);
+            } else {
+                throw new LogicException(sprintf("%s does not exist", $argAlias));
```
Comment (greg0ire) [inline src/Internal/Hydration/AbstractHydrator.php]:
```suggestion
                throw new LogicException(sprintf('%s does not exist', $argAlias));
```

File: tests/Tests/Models/CMS/CmsAddressDTO.php [hunk 9]
```diff
@@ -6,7 +6,7 @@
 
 class CmsAddressDTO
 {
-    public function __construct(public string|null $country = null, public string|null $city = null, public string|null $zip = null, public CmsAddressDTO|string|null $address = null)
+    public function __construct(public string|null $country = null, public string|null $city = null, public string|null $zip = null, public CmsDumbDTO|null $other = null)
```
Comment (SenseException) [inline tests/Tests/Models/CMS/CmsAddressDTO.php]: Why the change with `CmsDumbDTO`?

File: src/Query/ResultSetMapping.php (hunk 6 above)
Comment (SenseException) [reply src/Query/ResultSetMapping.php:167]: @greg0ire Not sure what you mean with "". :sweat_smile: 

This comment got resolved by @eltharin, but I don't understand why.

File: src/Internal/Hydration/AbstractHydrator.php [hunk 10]
```diff
@@ -336,21 +347,20 @@ protected function gatherRowData(array $data, array &$id, array &$nonemptyCompon
...
-            if (! isset($rowData['newObjects'][$ownerIndex . ':' . $argIndex])) {
-                continue;
+        $nestedEntities = [];
+        foreach ($this->resultSetMapping()->nestedNewObjectArguments as ['ownerIndex' => $ownerIndex, 'argIndex' => $argIndex, 'argAlias' => $argAlias]) {
+            if (array_key_exists($argAlias, $rowData['newObjects'])) {
+                ksort($rowData['newObjects'][$argAlias]['args']);
+                $rowData['newObjects'][$ownerIndex]['args'][$argIndex] = $rowData['newObjects'][$argAlias]['class']->newInstanceArgs($rowData['newObjects'][$argAlias]['args']);
+                unset($rowData['newObjects'][$argAlias]);
+            } else {
+                throw new LogicException(sprintf('%s does not exist', $argAlias));
```
Comment (SenseException) [inline src/Internal/Hydration/AbstractHydrator.php]: Could you please cover this exception case? This seems to be important for the code

**Review by SenseException — CHANGES_REQUESTED** [review]

File: tests/Tests/Models/CMS/CmsAddressDTO.php (hunk 9 above)
Comment (eltharin) [reply tests/Tests/Models/CMS/CmsAddressDTO.php]: address in address was never used and never tested, and In last PR I add CmsAddressDTO as type for that but a CmsAddressDTO in a CmsAddressDTO dosn't have sense. 
So I change it, 
I you want I can set : `public string|null $address = null, public CmsDumbDTO|null $other = null`

File: src/Internal/Hydration/AbstractHydrator.php (hunk 10 above)
Comment (eltharin) [reply src/Internal/Hydration/AbstractHydrator.php]: can't be reachable for the moment ;)

File: tests/Tests/Models/CMS/CmsAddressDTO.php (hunk 9 above)
Comment (eltharin) [reply tests/Tests/Models/CMS/CmsAddressDTO.php]: it's done

File: src/Query/ResultSetMapping.php (hunk 6 above)
Comment (eltharin) [reply src/Query/ResultSetMapping.php:167]: I remove class-string for juste string ?

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @eltharin !
