### PR TITLE
fix: handling of empty array in SQL condition generation

### LINKED ISSUE #12245: 2.20.7 / 3.5.3 seems to break EntityRepository::findBy... Empty Array Queries
### Bug Report

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 2.20.7
| Previous Version if the bug is a regression | 2.20.6

#### Summary

The latest release seems to have a regression in it which breaks some of our code.

I debugged through the changes and it seems be related to: https://github.com/doctrine/orm/pull/11895

#### Current behavior

```bash
  Exception: An exception occurred while executing a query: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ")"
  LINE 1: ...anger AS iduserschanger_8 FROM me_media t0 WHERE t0.id IN ()
```

#### Expected behavior

No error.

See also: https://github.com/doctrine/orm/pull/12190#issuecomment-3455298734

#### How to reproduce

```bash
git clone git@github.com:sulu/sulu.git
cd sulu
git checkout 3.0

docker compose up --wait

bin/runtests -i -t ContactBundle -C --flags="--filter=ContactControllerTest::testPostAccountIDNull"
```

### PR DESCRIPTION
**Pull request by elliotbruneel**
Fix a regression introduced in #12190: `$repository->findBy(['uuid' => []]` should be a valid expression and return an empty result.

Fixes #12245, with additional discussion at https://github.com/doctrine/orm/pull/12190#issuecomment-3455298734.

### CODE REVIEW

File: tests/Tests/ORM/Persisters/BasicEntityPersisterTypeValueSqlTest.php
Comment (greg0ire) [inline tests/Tests/ORM/Persisters/BasicEntityPersisterTypeValueSqlTest.php:1]: There should probably be a functional test for this. That way we'll be sure it works with all database platforms.

File: src/Persisters/Entity/BasicEntityPersister.php [hunk 1]
```diff
@@ -1753,13 +1753,19 @@ public function getSelectConditionStatementSQL($field, $value, $assoc = null, $c
...
+                }
+
                 $nullKeys      = array_keys($value, null, true);
                 $nonNullValues = array_diff_key($value, array_flip($nullKeys));
 
                 $placeholders = implode(', ', array_fill(0, count($nonNullValues), $placeholder));
 
                 $in = $column . ' ' . sprintf(self::$comparisonMap[$comparison], $placeholders);
 
+                // @phpstan-ignore if.alwaysTrue (false positive)
```
Comment (elliotbruneel) [inline src/Persisters/Entity/BasicEntityPersister.php]: @greg0ire  PHPStan reports a false positive error. Does this look correct to you?

Edit: i moved it in phpstan baseline

Comment (elliotbruneel) [reply src/Persisters/Entity/BasicEntityPersister.php]: phpstan fixed it but current version (2.1.22) does not contains the phpstan fix: https://github.com/phpstan/phpstan-src/pull/4295.

it's released from phptan 2.1.23 https://github.com/phpstan/phpstan-src/blob/2.1.23/src/Type/Accessory/NonEmptyArrayType.php

Comment (greg0ire) [reply src/Persisters/Entity/BasicEntityPersister.php]: Well then bump the phpstan version?

Comment (elliotbruneel) [reply src/Persisters/Entity/BasicEntityPersister.php]: I have updated phpstan to 2.1.23 and regenerate the baseline

**Review by SenseException — DISMISSED** [review]

**Comment by greg0ire** [comment]
@mpdude please review

**Comment by webmake** [comment]
Unfortunately, provided solution doesn't work in our use case, same error: `Syntax error`

**Comment by elliotbruneel** [comment]
> Unfortunately, provided solution doesn't work in our use case, same error: `Syntax error`

Can you give me more details, like which database system you’re using and when this happened?

**Comment by whataboutpereira** [comment]
I can confirm that it works here with MySQL, ORM v3.5.3.

File: src/Persisters/Entity/BasicEntityPersister.php [hunk 2]
```diff
@@ -1753,6 +1753,11 @@ public function getSelectConditionStatementSQL($field, $value, $assoc = null, $c
                     $value = [$value];
                 }
 
+                if (empty($value)) {
```
Comment (whataboutpereira) [inline src/Persisters/Entity/BasicEntityPersister.php]: Might compare array with === [] here.

**Comment by webmake** [comment]
> > Unfortunately, provided solution doesn't work in our use case, same error: `Syntax error`
> 
> Can you give me more details, like which database system you’re using and when this happened?

It looks like additional loop in `expandParameters` caused not resolved types in `inferParameterTypes` because giving one value - it returns types as array uuid_binary_ordered_time as string, while in older version it returns object typeOf UuidBinaryOrderedTimeType
image

image


it worked in doctrine/orm 2.20.6, and stopped working in doctrine/orm 2.20.7. Only one dependency updated.
we are using additionally ramsey/uuid-doctrine:1.8.2

**Comment by elliotbruneel** [comment]
> > > Unfortunately, provided solution doesn't work in our use case, same error: `Syntax error`
> > 
> > 
> > Can you give me more details, like which database system you’re using and when this happened?
> 
> It looks like additional loop in `expandParameters` caused not resolved types in `inferParameterTypes` because giving one value - it returns types as array uuid_binary_ordered_time as string, while in older version it returns object typeOf UuidBinaryOrderedTimeType [...]
> 
> it worked in doctrine/orm 2.20.6, and stopped working in doctrine/orm 2.20.7. Only one dependency updated. we are using additionally ramsey/uuid-doctrine:1.8.2

I cannot reproduce your issue and it's not directetly related to my fix. Maybe create another issue ?

i have tested with https://github.com/ramsey/uuid-doctrine/tree/main?tab=readme-ov-file#innodb-optimised-binary-uuids---deprecated and i cannot reproduce it.

I have tried

```php
<?php

declare(strict_types=1);

namespace Doctrine\Tests\ORM\Functional\Ticket;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\Type;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;
use Doctrine\Tests\OrmFunctionalTestCase;

use function random_bytes;

class GH12254Test extends OrmFunctionalTestCase
{
    protected function setUp(): void
    {
        if (Type::hasType('uuid_binary_ordered_time')) {
            Type::overrideType('uuid_binary_ordered_time', UuidType::class);
        } else {
            Type::addType('uuid_binary_ordered_time', UuidType::class);
        }

        parent::setUp();

        $this->setUpEntitySchema([
            GH12254EntityB::class,
        ]);

        $this->_em->getConnection()->getDatabasePlatform()->registerDoctrineTypeMapping('uuid_binary_ordered_time', 'binary');
    }

    public function testGetTypeForUuidBinaryOrderedTimeType(): void
    {
        $entity     = new GH12254EntityB();
        $entity->id = random_bytes(16);

        $this->_em->persist($entity);
        $this->_em->flush();

        $result         = $this->_em->getRepository(GH12254EntityB::class)->findBy(['id' => []]);
        $resultNonEmpty = $this->_em->getRepository(GH12254EntityB::class)->findBy(['id' => [$entity->id]]);

        $this->assertEmpty($result);
        $this->assertCount(1, $resultNonEmpty);
    }
}


/**
 * @Entity()
 */
class GH12254EntityB
{
    /**
     * @Column(type="uuid_binary_ordered_time")
     * @Id()
     * @GeneratedValue(strategy="NONE")
     * @var UUidType
     */
    public $id = null;
}

class UUidType extends Type
{
    public const NAME = 'uuid_binary_ordered_time';

    public function getName(): string
    {
        return self::NAME;
    }

    public function getSQLDeclaration(array $column, AbstractPlatform $platform): string
    {
        return $platform->getBinaryTypeDeclarationSQL(
            [
                'length' => 16,
                'fixed' => true,
            ]
        );
    }
}

```

**Comment by webmake** [comment]
It could be unrelated, I think it's working for you, because it's simple case, but Ramsey has `convertToDatabaseValue` and it passes binary string https://github.com/ramsey/uuid-doctrine/blob/1.8.2/src/UuidBinaryOrderedTimeType.php#L110 instead of type or uuid string format

**Comment by webmake** [comment]
Sorry for confusion, I retract all my comments, it looks like we had bugfix, which doesn't work anymore. But thanks for fixing things! :heart:

**Comment by mpdude** [comment]
@elliotbruneel Thank you for working on this!

Two remarks, probably a matter of personal preference:

1) I'd prefer using `1=0` over `IN (NULL)`. To me, that makes the intent more clear. I don't know if it would be better portable as well.

2) We could amend the `\Doctrine\Tests\ORM\Persisters\BasicEntityPersisterTypeValueSqlTest::testSelectConditionStatementWithMultipleValuesContainingNull` test where the logic in question has been covered before.

If you're looking for a suggestion, you may want to check https://github.com/doctrine/orm/compare/2.20.x...mpdude:doctrine2:fix-12190-regression?expand=1.

**Comment by mpdude** [comment]
Just noticed that `IN (NULL)` was the SQL we generated before. So, obviously, it's sufficiently portable, at least nobody complained.

**Comment by elliotbruneel** [comment]
> Just noticed that `IN (NULL)` was the SQL we generated before. So, obviously, it's sufficiently portable, at least nobody complained.

My first goal was indeed to keep original generated code. I have edited the logic as it's more clear

File: phpstan-baseline.neon [hunk 3]
```diff
@@ -1056,6 +1056,12 @@ parameters:
 			count: 1
 			path: src/Internal/HydrationCompleteHandler.php
```
Comment (mpdude) [inline phpstan-baseline.neon:1058]: Where's that coming from? Maybe you need to rebase to make it go away?

Comment (elliotbruneel) [reply phpstan-baseline.neon:1058]: It's come from the update of phpstan to 2.1.23

**Review by mpdude — APPROVED** [review]
:+1: for the functional aspects, thank you.

Regarding PHPStan, @greg0ire please decide whether it makes sense in this PR

**Comment by greg0ire** [comment]
@mpdude as long as it is in a separate commit, which is the case, I'm satisfied.

**Comment by greg0ire** [comment]
Thanks @elliotbruneel !

**Comment by zerkms** [comment]
@mpdude `IN (NULL)` is guaranteed to not match any rows. And `IN (1=0)` would match "falsy" (or real boolean `false`) values, depending on the DBMS.

**Comment by mpdude** [comment]
Not `IN(1=0)`, only `1=0`

**Comment by zerkms** [comment]
@mpdude 

postgresql:

```sql
# SELECT * FROM unnest(ARRAY[true, false]) AS t(col) WHERE col IN (1=0);
 col 
-----
 f
(1 row)

# SELECT * FROM unnest(ARRAY[null, true, false]) AS t(col) WHERE col IN (null);
 col 
-----
(0 rows)

```

@mpdude oh I see now, the suggestion was not to have `IN (...)` operator at all, just `1=0` expression. Right, my fault.
