### PR TITLE
Redeclare `$_attributes` property in `Configuration` class.

### LINKED ISSUE #8884: Get Psalm job to pass with DBAL 3
[Recently, a CI job was added on the 2.10.x branch to statically analyze this project after forcing the installation of `doctrine/dbal` v3](https://github.com/doctrine/orm/pull/8874).

In order not to disrupt contributors, we made sure it would not fail the build although it really does not pass at all:

https://github.com/doctrine/orm/blob/e09f126abfec0add53dc1ed8d4e3708117032fc1/.github/workflows/static-analysis.yml#L94

If you want to help us fix it or get closer to fixing it, you can reproduce the failures locally by running (from the 2.10.x branch)

```shell
composer require doctrine/dbal ^3.0
vendor/bin/psalm
```

When this issue is fixed, we should create a new one about making this job no longer experimental.

### LINKED ISSUE #8885: Get Phpstan job to pass with DBAL 3
[Recently, a CI job was added on the 2.10.x branch to statically analyze this project after forcing the installation of `doctrine/dbal` v3](https://github.com/doctrine/orm/pull/8874).

In order not to disrupt contributors, we made sure it would not fail the build although it really does not pass at all:

https://github.com/doctrine/orm/blob/e09f126abfec0add53dc1ed8d4e3708117032fc1/.github/workflows/static-analysis.yml#L52

If you want to help us fix it or get closer to fixing it, you can reproduce the failures locally by running (from the 2.10.x branch)

```shell
composer require doctrine/dbal ^3.0
vendor/bin/phpstan
```

When this issue is fixed, we should create a new one about making this job no longer experimental.

### PR DESCRIPTION
**Pull request by scyzoryck**
Hello. 

doctrine/dbal:3.x removed `$_attributes` property in a `Configuration` class that we are extending in: https://github.com/doctrine/dbal/commit/5d03f6e443e8d444bf9917ca44b1b553ecaa4896

Lets redeclare it to keep backward compatibility and fix 65 of ot 110 following Psalm errors. 
```
[0;31mERROR[0m: UndefinedThisPropertyFetch - lib/Doctrine/ORM/Configuration.php:66:9 - Instance property Doctrine\ORM\Configuration::$_attributes is not defined (see https://psalm.dev/041)
        [97;41m$this->_attributes[0m['proxyDir'] = $dir;


[0;31mERROR[0m: UndefinedThisPropertyAssignment - lib/Doctrine/ORM/Configuration.php:66:9 - Instance property Doctrine\ORM\Configuration::$_attributes is not defined (see https://psalm.dev/040)
        [97;41m$this->_attributes[0m['proxyDir'] = $dir;
```
As a next step - I think we should deprecate usage of this property 2.10 and start using separate properties in 3.x similar to doctrine/dbal.

### CODE REVIEW

File: lib/Doctrine/ORM/Configuration.php [hunk 1]
```diff
@@ -54,6 +54,9 @@
  */
 class Configuration extends \Doctrine\DBAL\Configuration
 {
+    /** @var mixed[] */
+    protected $_attributes = []; /** @codingStandardsIgnoreLine */
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Configuration.php]: Please use an ignore rule in `phpcs.xml.dist` for this.

```suggestion
    protected $_attributes = [];
```

Comment (scyzoryck) [reply lib/Doctrine/ORM/Configuration.php]: @greg0ire - thanks, changed. :)

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @scyzoryck !
