### PR TITLE
Fix changeset computation for enum arrays

### LINKED ISSUE #10251: UnitOfWork still not right - probably Enum-related
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.13.2 and .3 and .4

#### Summary

I think I'm observing the same issue as https://github.com/doctrine/orm/issues/10124, but it wasn't fixed by 2.13.4, so I'm posting it separately.

I have a table with some thousand entries, and when I change a single one (through a Symfony form), *all* are getting "updated" (i.e. overwritten with their current values). 

The last version, which really works for me, is 2.13.1.

2.13.2 introduced the error:

> "Hearts,Clubs" is not a valid backing value for enum "App\Suit"

This was fixed in 2.13.3, but since then, persisting a single changed entity takes several minutes.

#### How to reproduce

I tried `dd($this->getEntityManager()->getUnitOfWork());`, but couldn't find any differences between the working and non-working versions - where should I look at to provide more information?

### PR DESCRIPTION
**Pull request by michnovka**
Fix https://github.com/doctrine/orm/issues/10251

### CODE REVIEW

File: lib/Doctrine/ORM/UnitOfWork.php [hunk 1]
```diff
@@ -744,8 +744,18 @@ public function computeChangeSet(ClassMetadata $class, $entity)
 
                 $orgValue = $originalData[$propName];
 
-                if ($orgValue instanceof BackedEnum) {
-                    $orgValue = $orgValue->value;
+                if (! empty($class->fieldMappings[$propName]['enumType'])) {
```
Comment (michnovka) [inline lib/Doctrine/ORM/UnitOfWork.php:747]: if somebody is interested why I added this check, its because I want to avoid the case where we have an array and go over the whole array checking if its `BackedEnum` for no reason. This way, unless there are enums in the play for the given field, no checks whatsoever are performed. Likely 0 performance gains with simple enums, but large performance gain with arrays of enums.

**Comment by michnovka** [comment]
@greg0ire please review

**Comment by greg0ire** [comment]
> Fix changeset computation for enum arrays

Please explain how it is broken, and what solution you applied in the commit message. I will review when that's done.

**Comment by michnovka** [comment]
@greg0ire done

File: lib/Doctrine/ORM/UnitOfWork.php [hunk 2]
```diff
@@ -804,6 +814,7 @@ public function computeChangeSet(ClassMetadata $class, $entity)
                     }
 
                     if ($orgValue !== null && $assoc['orphanRemoval']) {
+                        /** @psalm-var object $orgValue */
```
Comment (greg0ire) [inline lib/Doctrine/ORM/UnitOfWork.php]: We usually use `assert` instead of `@var`.

```suggestion
                        assert(is_object($orgValue));
```

**Comment by greg0ire** [comment]
@ThomasLandauer can you please test this?

**Review by greg0ire — APPROVED** [review]

**Comment by michnovka** [comment]
> @ThomasLandauer can you please test this?

I have tested it on https://github.com/ThomasLandauer/doctrine-issue-10251 and it did fix the issue

**Comment by michnovka** [comment]
can we add this on 2.13.5 milestone?

**Comment by greg0ire** [comment]
We usually do this right after merging.

**Review by SenseException — APPROVED** [review]

**Review by derrabus — APPROVED** [review]
