### PR TITLE
Fix remaining usages of deprecated ClassLoader and Inflector from doctrine/common

### LINKED ISSUE #7306: ClassMetadataInfo uses deprecated doctrine/common class
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.6.2

#### Summary

After upgrading to 2.6.2, which included an upgrade to doctrine/common:2.9.0, PHPUnit now fails with:
`  1x: Doctrine\Common\ClassLoader is deprecated.`

#### Previous behavior

No deprecation errors were shown from using non-deprecated methods

#### Current behavior

```
Doctrine\Common\ClassLoader is deprecated
/Users/simon/projects/stokl/backend/vendor/doctrine/common/lib/Doctrine/Common/ClassLoader.php:7
/Users/simon/projects/stokl/backend/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php:1028
/Users/simon/projects/stokl/backend/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:266
/Users/simon/projects/stokl/backend/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:245
/Users/simon/projects/stokl/backend/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:305
/Users/simon/projects/stokl/backend/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:78
/Users/simon/projects/stokl/backend/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:183
/Users/simon/projects/stokl/backend/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:89
```
#### How to reproduce

This is from in a test case in a Symfony application

```
    $entityManager =
      $kernel->getContainer()->get('doctrine.orm.entity_manager');

    $metadatas = $entityManager->getMetadataFactory()->getAllMetadata();
```

### PR DESCRIPTION
**Pull request by Majkl578**
Fixes #7306.

### CODE REVIEW

**Review by jwage — APPROVED** [review]

**Review by lcobucci — APPROVED** [review]

File: lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php [hunk 1]
```diff
@@ -1025,7 +1024,11 @@ public function validateIdentifier()
     public function validateAssociations()
     {
         foreach ($this->associationMappings as $mapping) {
-            if ( ! ClassLoader::classExists($mapping['targetEntity']) ) {
+            if (
+                ! class_exists($mapping['targetEntity'])
+                && ! interface_exists($mapping['targetEntity'])
+                && ! trait_exists($mapping['targetEntity'])
```
Comment (stof) [inline lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php]: I don't think targeting a trait is actually supported btw

Comment (Majkl578) [reply lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php]: Agreed, kept it for compat with `ClassLoader::classExists()`.
