### PR TITLE
Ignore subclasses without discriminatorValue when generating discriminator column condition SQL

### LINKED ISSUE #10846: Discriminator column empty value "IN" query
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.14.2

#### Summary

DiscriminatorMap adding empty value (`''`) to SQL query example: 
```
Executing query: SELECT o0_.id AS id_0, o0_.amount AS amount_1, o0_.depositAddress AS depositAddress_2, o0_.name AS name_3, o0_.network AS network_4, o0_.type AS type_5 FROM operations o0_ WHERE o0_.type IN ('blockchain-in', 'expense', '')
```

This leads to error `invalid input value` when using Enum for Postgres DB

#### Current behavior

Adding `o0_.type IN ('blockchain-in', 'expense', '')` is incorrect and should be `o0_.type IN ('blockchain-in', 'expense')`

#### How to reproduce

I create a repository with an easy way to reproduce this issue. 
It was introduced in version `2.14.2` prior to this version it was working as expected. 

You could verify it by cloning the repository: https://github.com/Legion112/doctrine-playground
After cloning use docker for quick setup:
```
make shell 
```
After running the command below in logs you could see a wrong select statement
```
composer require doctrine/orm:2.14.2 -W && php index.php
```

I have confirmed that this version correctly was formatted correctly 

#### Expected behavior
```
Executing query: SELECT o0_.id AS id_0, o0_.amount AS amount_1, o0_.depositAddress AS depositAddress_2, o0_.name AS name_3, o0_.network AS network_4, o0_.type AS type_5 FROM operations o0_ WHERE o0_.type IN ('blockchain-in', 'expense')
```

### LINKED ISSUE #11177: Abstract subclass discriminator value is null
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.17.3

#### Summary

In case we use single table inheritance we might have intermediate abstract class that is part of the discriminator map but value in that case is null. 

#### Current behavior

SqlWalker (https://github.com/htto/doctrine-orm/blob/1ae74b8ec56e8749d6c85c2845d64294ba34dd66/lib/Doctrine/ORM/Query/SqlWalker.php#L479) does not check if value is null and the following deprecation is emitted:
```
vendor/doctrine/dbal/src/Driver/PDO/Connection.php:89
PDO::quote(): Passing null to parameter #1 ($string) of type string is deprecated
```

#### Expected behavior

Skip null values in the map.
I believe fix can be adding a not null check:
```
foreach ($class->subClasses as $subclassName) {
    if ($this->em->getClassMetadata($subclassName)->discriminatorValue !== null) {
        $values[] = $conn->quote($this->em->getClassMetadata($subclassName)->discriminatorValue);
    }
}
```

I'am not familiar with the internals and there might be more places in the code that should be checked. If someone more experienced would like to give a suggestion, I can open a PR with the fix.
Thanks

### LINKED ISSUE #11199: Discriminator column condition SQL contains empty string when inheritance tree contains an abstract class non-root entity
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.14.2

#### Summary

after commit https://github.com/doctrine/orm/commit/4e8e3ef30b3d214640883aec5a17896afc006116 when `\Doctrine\ORM\Query\SqlWalker` generates dicsriminator column condition SQL (method `\Doctrine\ORM\Query\SqlWalker::generateDiscriminatorColumnConditionSQL`) it adds an empty string to the list of possible values if the inheritance hierarchy contains a non-root abstract class. when the discriminator column is implemented with a custom type in PostgreSQL (equivalent of Enum) the query fails because the type cannot have a value of an empty string. it boils down to the fact that `\Doctrine\ORM\Mapping\ClassMetadataInfo::$subClasses` contains an abstract class and in it's Metadata the value of `\Doctrine\ORM\Mapping\ClassMetadataInfo::$discriminatorValue` is `null`.

#### Previous behavior

In version 2.14.1 `\Doctrine\ORM\Mapping\ClassMetadataInfo::$subClasses` does not contain an abstract class.

#### Current behavior

As described in Summary

#### How to reproduce

Here are entity definitions necessary to reproduce the problem.
```php
/**
 * @ORM\Entity()
 * @ORM\Table(name="bug")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="asset_type", type="string")
 * @ORM\DiscriminatorMap({
 *     "foo" = "\Doctrine\Tests\ORM\Functional\Ticket\BugFoo",
 *     "bar" = "\Doctrine\Tests\ORM\Functional\Ticket\BugBar",
 *     "baz" = "\Doctrine\Tests\ORM\Functional\Ticket\BugBaz",
 * })
 */
class BugRoot
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @ORM\Column(type="integer")
     *
     * @var int|null
     */
    private $id = null;
}

/**
 * @ORM\Entity()
 */
abstract class BugParent extends BugRoot
{
}

/**
 * @ORM\Entity()
 */
class BugFoo extends BugParent
{
}

/**
 * @ORM\Entity()
 */
class BugBar extends BugParent
{
}

/**
 * @ORM\Entity()
 */
class BugBaz extends BugRoot
{
}

```

The simplest way to reproduce the problem is
```php
class BugTest extends OrmFunctionalTestCase
{
    protected function setUp(): void
    {
        parent::setUp();

        $this->setUpEntitySchema([
            BugRoot::class,
            BugParent::class,
            BugFoo::class,
            BugBar::class,
            BugBaz::class,
        ]);
    }

    public function testBug(): void
    {
        $this->getEntityManager()->createQuery('SELECT e FROM ' . BugRoot::class . ' e')->getSQL();
    }
}
```
if run from tag 2.14.2 the execution fails with
`PDO::quote(): Passing null to parameter #1 ($string) of type string is deprecated` which is caused by the issue described in Summary. If the deprecation is skipped, like it is in our production code, the empty string is added to discriminator column condition SQL.

when I have time I'll try to create a reproducer which ties directly to method `generateDiscriminatorColumnConditionSQL`

### PR DESCRIPTION
**Pull request by DemoniacDeath**
After commit https://github.com/doctrine/orm/commit/4e8e3ef30b3d214640883aec5a17896afc006116 when `\Doctrine\ORM\Query\SqlWalker` generates dicsriminator column condition SQL (method `\Doctrine\ORM\Query\SqlWalker::generateDiscriminatorColumnConditionSQL`) it adds an empty string to the list of possible values if the inheritance hierarchy contains a non-root abstract class. 

When the discriminator column is implemented with a custom type in PostgreSQL (equivalent of Enum) the query fails because the type cannot have a value of an empty string. It boils down to the fact that `\Doctrine\ORM\Mapping\ClassMetadataInfo::$subClasses` contains an abstract class and in its Metadata the value of `\Doctrine\ORM\Mapping\ClassMetadataInfo::$discriminatorValue` is `null`.

#### Previous behavior

In version 2.14.1 `\Doctrine\ORM\Mapping\ClassMetadataInfo::$subClasses` does not contain an abstract class.

Fixes #11199, fixes #11177, fixes #10846.

### CODE REVIEW

**Comment by mpdude** [comment]
I have a suggestion how I'd like to change your PR here:

https://github.com/DemoniacDeath/orm/pull/1/

If you like, you should be able to merge that PR into your own branch and it should be updated here.

Basically, I'd prefer to not check for `null` discriminator values, but instead check the fact that a class is abstract – like it is done when building or validating the discriminator map.

Additionally, I discovered the edge case that you might end up with no possible class at all.

**Review by mpdude — DISMISSED** [review]
LGTM!

**Comment by mpdude** [comment]
Maintainers: We probably should squash-merge this, keeping the text from the initial comment as the commit message.

**Comment by mpdude** [comment]
Does this also fix #11177?

**Comment by mpdude** [comment]
#10846 is probably also the same

**Comment by plantas** [comment]
This PR fixes https://github.com/doctrine/orm/issues/11177 too 👍

**Comment by mpdude** [comment]
* What if the class metadata is taken from the cache - may that cause reflection not to be initialized, and may that lead to wrong results?
* When metadata comes from the cache, does the reflection-based check trigger the autoloader/class load that we might want to avoid?

-> Looking at the discriminator value might be a better way to go.

On the other hand, there may be users that put abstract classes into the Discriminator Map, which was a recommendation for some time... would it make sense to skip those classes? Probably we can neglect the performance difference.

Are there any other reasons why the discriminator value might be `null`, can the Discriminator Map be mis-configured in a stupid way?

**Comment by mpdude** [comment]
I was unable to get `null` values into the DM through configuration, it always ended up as the `0` key or a `'null'` string. So, `null` seems to be a safe indication that the class is not in the map.

The map is checked at load time that all intermediate, non-abstract entity classes have been declared, so this seems to be safe.

**Review by mpdude — DISMISSED** [review]

**Comment by mpdude** [comment]
~#10643 is a very similar fix in another place… does this show additional refactorings would be appropriate?~

#11213

File: lib/Doctrine/ORM/Query/SqlWalker.php [hunk 1]
```diff
@@ -476,14 +480,22 @@ private function generateDiscriminatorColumnConditionSQL(array $dqlAliases): str
...
+                // from the discriminator map. In that case, they have a null discriminator value.
+                if ($subclassMetadata->discriminatorValue === null) {
+                    continue;
+                }
 
-            $sqlParts[] = $sqlTableAlias . $class->getDiscriminatorColumn()['name'] . ' IN (' . implode(', ', $values) . ')';
+                $values[] = $conn->quote($subclassMetadata->discriminatorValue);
+            }
+
+            if ($values) {
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Query/SqlWalker.php]: I think I wouldn't rely on a boolean cast here, and instead either use `count($values) > 0` or `$values === []` (and invert the condition).

Comment (mpdude) [reply lib/Doctrine/ORM/Query/SqlWalker.php]: fixed

**Review by greg0ire — APPROVED** [review]

**Review by mpdude — APPROVED** [review]

**Comment by mpdude** [comment]
@DemoniacDeath congratulations, you’re now a Doctrine ORM contributor. Keep it up!

🚀

**Comment by Legion112** [comment]
Big shout out to the contributors 🙇‍♂️
