### PR TITLE
[GH-9219] Add support for toIterable over mixed or scalar results.

### LINKED ISSUE #9219: AbstractQuery::toIterable is not a full replacement for AbstractQuery::iterate
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes (kind of)
| Version     | 2.10.2

#### Summary

The new `AbstractQuery::toIterable` method does not support hydrating mixed results, while the deprecated `AbstractQuery::iterate` was supporting it. This means that it is not always possible to migrate from the deprecated API to its replacement API (and so that some cases would not be possible in ORM 3.0).

It would be great to support it.

### PR DESCRIPTION
**Pull request by beberlei**
`AbstractHydrator::hydrateRowData` will return `$result` in a very weird way based on combinations of objects, cross joined objects or scalar results. This is already "worked on" in `AbstractHydrator::toIterable` but it needs a bunch more molding to make scalar results and multiple object results work.

Fixes #9219
Fixes https://github.com/doctrine/orm/issues/8520

### CODE REVIEW

File: tests/Tests/ORM/Functional/QueryTest.php [hunk 1]
```diff
@@ -403,11 +403,126 @@ public function testToIterableWithMultipleSelectElements(): void
 
     public function testToIterableWithMixedResultIsNotAllowed(): void
```
Comment (stof) [inline tests/Tests/ORM/Functional/QueryTest.php]: Test names must be updated to reflect what they actually cover

**Review by stof — APPROVED** [review]

**Review by greg0ire — APPROVED** [review]
