### PR TITLE
Fix variadic args in Expr

### LINKED ISSUE #8537: Replace some usages of func_get_args() with variadics
See https://github.com/doctrine/orm/search?q=func_get_args

This will be a breaking change, and as such should target 3.0.x

### PR DESCRIPTION
**Pull request by simPod**
Closes #8537

### CODE REVIEW

File: lib/Doctrine/ORM/Query/Expr.php [hunk 1]
```diff
@@ -45,13 +46,11 @@ class Expr
...
-     *                                                               but requires at least one defined
-     *                                                               when converting to string.
-     *
-     * @return Expr\Andx
+     * @param Expr\Comparison|Expr\Func|Expr\Andx|Expr\Orx|string ...$x Optional clause. Defaults to null,
+     *                                                                  but requires at least one defined
+     *                                                                  when converting to string.
      */
-    public function andX($x = null)
+    public function andX(...$x) : Expr\Andx
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Query/Expr.php:53]: This is a BC break for extending classes, and cannot go into 2.8 as such: https://3v4l.org/be7cf

Comment (simPod) [reply lib/Doctrine/ORM/Query/Expr.php:34]: I have changed the target

File: lib/Doctrine/ORM/Query/Expr.php [hunk 2]
```diff
@@ -31,14 +31,11 @@ class Expr
...
-     *
-     * @return Expr\Andx
+     * @param Expr\Comparison|Expr\Func|Expr\Andx|Expr\Orx|string ...$x Optional clause. Defaults to null,
+     *                                                                  but requires at least one defined
+     *                                                                  when converting to string.
      */
-    public function andX($x = null)
+    public function andX(...$x): Expr\Andx
     {
         return new Expr\Andx(func_get_args());
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Query/Expr.php]:
```suggestion
        return new Expr\Andx($x);
```

File: lib/Doctrine/ORM/Query/Expr.php [hunk 3]
```diff
@@ -52,14 +49,11 @@ public function andX($x = null)
...
-     *
-     * @return Expr\Orx
+     * @param Expr\Comparison|Expr\Func|Expr\Andx|Expr\Orx|string ...$x Optional clause. Defaults to null,
+     *                                                                  but requires at least one defined
+     *                                                                  when converting to string.
      */
-    public function orX($x = null)
+    public function orX(...$x): Expr\Orx
     {
         return new Expr\Orx(func_get_args());
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Query/Expr.php]:
```suggestion
        return new Expr\Orx($x);
```

**Comment by greg0ire** [comment]
Please document the BC-break in UPGRADE.md

File: UPGRADE.md [hunk 4]
```diff
@@ -1,5 +1,7 @@
 # Upgrade to 3.0
 
+Method `Doctrine\ORM\Query\Expr#andX()` and `Doctrine\ORM\Query\Expr#orX()` uses variadic argument in its signature (`...$x`)
```
Comment (greg0ire) [inline UPGRADE.md]:
```suggestion
## Variadic methods now use native variadics
Methods `Doctrine\ORM\Query\Expr#andX()` and `Doctrine\ORM\Query\Expr#orX()` were using `func_get_args()` to simulate a variadic argument. A variadic argument is now actually used in their signatures signature (`...$x`).
Signatures of overridden methods should be changed accordingly
```

**Comment by greg0ire** [comment]
This looks related to https://github.com/doctrine/orm/issues/8537 , there are a few more methods that could benefit from this change in `lib/Doctrine/ORM/QueryBuilder.php`, would you like to also take care of those in this PR?

**Comment by simPod** [comment]
Aight

**Comment by simPod** [comment]
There are also `select()`, `addSelect()`, `where()` and `having()` using `func_get_args()` in one path. Do you want them rewritten as well?

**Comment by greg0ire** [comment]
Yes please! From what I see, that would be a really nice simplification, right?

File: UPGRADE.md [hunk 5]
```diff
@@ -1,5 +1,10 @@
 # Upgrade to 3.0
 
+## Variadic methods now use native variadics
+Methods `Doctrine\ORM\Query\Expr#andX()`, `Doctrine\ORM\Query\Expr#orX()`, `Doctrine\ORM\QueryBuilder#select()`, `Doctrine\ORM\QueryBuilder#addSelect()`, `Doctrine\ORM\QueryBuilder#where()`, `Doctrine\ORM\QueryBuilder#andWhere()`, `Doctrine\ORM\QueryBuilder#orWhere()`, `Doctrine\ORM\QueryBuilder#groupBy()`, `Doctrine\ORM\QueryBuilder#andGroupBy()`, `Doctrine\ORM\QueryBuilder#having()`, `Doctrine\ORM\QueryBuilder#andHaving()` and `Doctrine\ORM\QueryBuilder#orHaving()` were using `func_get_args()` to simulate a variadic argument.
```
Comment (greg0ire) [inline UPGRADE.md]:
```suggestion
The following methods were using `func_get_args()` to simulate a variadic argument:
- `Doctrine\ORM\Query\Expr#andX()`
- `Doctrine\ORM\Query\Expr#orX()`
- `Doctrine\ORM\QueryBuilder#select()`
- `Doctrine\ORM\QueryBuilder#addSelect()`
- `Doctrine\ORM\QueryBuilder#where()`
- `Doctrine\ORM\QueryBuilder#andWhere()`
- `Doctrine\ORM\QueryBuilder#orWhere()`
- `Doctrine\ORM\QueryBuilder#groupBy()`
- `Doctrine\ORM\QueryBuilder#andGroupBy()`
- `Doctrine\ORM\QueryBuilder#having()`
- `Doctrine\ORM\QueryBuilder#andHaving()`
- `Doctrine\ORM\QueryBuilder#orHaving()` 
```

**Review by greg0ire — DISMISSED** [review]
The code looks good to me, let's rework the UPGRADE and squash?

**Comment by simPod** [comment]
Done, thank you

**Review by greg0ire — DISMISSED** [review]

File: lib/Doctrine/ORM/QueryBuilder.php [hunk 6]
```diff
@@ -797,13 +794,11 @@ public function addSelect($select = null)
     {
         $this->_type = self::SELECT;
 
-        if (empty($select)) {
+        if ($select === []) {
```
Comment (SenseException) [inline lib/Doctrine/ORM/QueryBuilder.php:797]: Was this method supposed to be variadic too that you changed this check?

Comment (greg0ire) [reply lib/Doctrine/ORM/QueryBuilder.php:797]: I don't really understand your question, but I think it was supposed to be variadic too since there was a call to `func_get_args()`

Comment (SenseException) [reply lib/Doctrine/ORM/QueryBuilder.php:797]: I couldn't write my comment on the method itself.

@simPod please change `addSelect($select = null)` to `addSelect(...$select)`

**Review by SenseException — CHANGES_REQUESTED** [review]

File: lib/Doctrine/ORM/QueryBuilder.php (hunk 6 above)
Comment (greg0ire) [reply lib/Doctrine/ORM/QueryBuilder.php:797]: Oh… right!

Comment (simPod) [reply lib/Doctrine/ORM/QueryBuilder.php:797]: ohlol, nice catch

Comment (simPod) [reply lib/Doctrine/ORM/QueryBuilder.php:797]: I've checked the rest has updated signature and docblock

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @simPod !

File: lib/Doctrine/ORM/QueryBuilder.php [hunk 7]
```diff
@@ -740,21 +739,19 @@ public function add($dqlPartName, $dqlPart, $append = false)
...
             return $this;
         }
 
-        $selects = is_array($select) ? $select : func_get_args();
-
-        return $this->add('select', new Expr\Select($selects), false);
+        return $this->add('select', new Expr\Select($select), false);
```
Comment (ondrejmirtes) [inline lib/Doctrine/ORM/QueryBuilder.php:754]: Hi, are you sure you haven't done a mistake here? I'm seeing a bug related to this place: https://github.com/doctrine/orm/issues/11241

Comment (simPod) [reply lib/Doctrine/ORM/QueryBuilder.php:754]: Possible, I'll take a look.
