### PR TITLE
[GH-11185] Bugfix: do not use collection batch loading for indexBy association

### LINKED ISSUE #11097: `OneToMany::indexBy` no longer works when refering a database column
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.17.0

#### Summary

Indexing by database column worked, now it doesn't.
Better look at previous/current behavior.

#### Previous behavior

```php
class Language
{
    #[ORM\Id]
    #[ORM\Column(type: 'string', length: 20)]
    private ?string $id = null;
}

class Product {
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer', options: ['unsigned' => true])]
    private ?int $id = null;

    #[ORM\OneToMany(
        mappedBy: 'product',
        targetEntity: ProductTranslation::class,
        cascade: ['persist', 'merge'],
        fetch: 'EAGER',
        indexBy: 'language_id'
    )]
    private Collection $translations;
}

class ProductTranslation {
    #[ORM\Id]
    #[ORM\ManyToOne(targetEntity: Product::class, inversedBy: 'translations')]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    private Product $product;

    #[ORM\Id]
    #[ORM\ManyToOne(targetEntity: Language::class)]
    #[ORM\JoinColumn(nullable: false)]
    private Language $language;
}
```

This worked, indexing `Product::$translations` by `language_id` (`Language::$id`).

#### Current behavior

I get a warning and an error:

```txt
Warning: Undefined array key "language_id"
vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php:846
```

```txt
Error: Call to a member function getValue() on null
vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:3195
```

#### How to reproduce

I've created a simple symfony project: https://github.com/aprat84/doctrine-2.17-bug

- Clone it
- Execute migrations
- Execute tests in each commit (one for 2.16.3 and one for 2.17.1)

### LINKED ISSUE #11149: Doctrine ORM 2.17.x Update Causes TypeError with indexBy on Doctrine Type (custom UUID)
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.17.x

#### Summary
After updating doctrine/orm to version 2.17.x, the index-by for doctrine type stopped working even though the object (custom UUID) has the __toString() method. Up to version 2.16.x everything worked fine.

`TypeError: Doctrine\Common\Collections\ArrayCollection::set(): Argument #1 ($key) must be of type string|int, App\Common\Domain\Uuid given, called in /home/xxx/vendor/doctrine/orm/lib/Doctrine/ORM/PersistentCollection.php on line 191`

#### Previous behavior

Until version 2.16.x, indexBy for doctrine type objects (custom UUID) with the __toString() method worked fine.

```xml
<one-to-many field="subaccountRecipients" target-entity="App\Message\Preparation\Domain\SubaccountRecipient" mapped-by="message" fetch="EAGER" orphan-removal="true" index-by="subaccountRecipientId">
            <cascade>
                <cascade-persist />
                <cascade-remove />
            </cascade>
        </one-to-many>
```

#### Current behavior

Currently, Doctrine is unable to read such an object and shows an error. Before creating an ArrayCollection, there is no cast to a simple type, in this case string.

`TypeError: Doctrine\Common\Collections\ArrayCollection::set(): Argument #1 ($key) must be of type string|int, App\Common\Domain\Uuid given, called in /home/xxx/vendor/doctrine/orm/lib/Doctrine/ORM/PersistentCollection.php on line 191`

#### How to reproduce

- Have an existing Symfony application using Doctrine 2.17.x
- Add in the indexBy field, which is an object mapped by doctrine type
- Use findOneBy method

### PR DESCRIPTION
**Pull request by beberlei**
Replaces #11185 

Fixes #11097 
Fixes #11149

Related:
* [https://github.com/doctrine/orm/pull/11289](https://github.com/doctrine/orm/pull/11289)
* #11149 
* #11097

### CODE REVIEW

**Review by greg0ire — DISMISSED** [review]

File: tests/Tests/ORM/Functional/Ticket/GH11149/EagerProduct.php [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+
+    /**
+     * @ORM\OneToMany(
+     *     targetEntity=EagerProductTranslation::class,
+     *     mappedBy="product",
+     *     fetch="EAGER",
+     *     indexBy="locale_code"
+     * )
+     *
+     * @var EagerProductTranslation[]|ArrayCollection
```
Comment (derrabus) [inline tests/Tests/ORM/Functional/Ticket/GH11149/EagerProduct.php]:
```suggestion
     * @var Collection<string, EagerProductTranslation>
```

**Review by derrabus — APPROVED** [review]
