### PR TITLE
Fix #9095 by re-applying #9096

### LINKED ISSUE #9095: Regression: abstract entities in the middle of a hierarchy need to be part of discriminator map
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.9.x, 2.10.x

#### Summary

As mentioned in https://github.com/doctrine/orm/issues/8771#issuecomment-933454924, there is a regression that affects both `2.9` and `2.10`:

If an entity hierarchy has an abstract entity class in the middle of the hierarchy, Doctrine complains that it must be part of the discriminator map. Example:

- abstract class `A`
    - abstract class `B`
        - class `C`

`bin/console doctrine:schema:validate` reports:

>  [FAIL] The entity-class B mapping is invalid:
> * Entity class 'B' is part of inheritance hierarchy, but is not mapped in the root entity 'A' discriminator map. All subclasses must be listed in the discriminator map.

This doesn't make sense, as there cannot be an entry in the database for an abstract entity class.

**This was working fine up to Doctrine `2.8`.**

The quick fix for those affected is to add "fake" entries to the discriminator map for abstract child entities, that do not have an equivalent in the database `ENUM`; which is rather ugly.

### PR DESCRIPTION
**Pull request by mpdude**
Since #10411 has been merged, no more need to specify all intermediate abstract entity classes.

Thus, we can relax the schema validator check as requested in #9095. The reasons given in #9142 to keep it no longer apply.

Fixes #9095.

### CODE REVIEW

File: lib/Doctrine/ORM/Tools/SchemaValidator.php [hunk 1]
```diff
@@ -253,7 +253,7 @@ public function validateClass(ClassMetadataInfo $class)
             }
         }
 
-        if (! $class->isInheritanceTypeNone() && ! $class->isRootEntity() && ! $class->isMappedSuperclass && array_search($class->name, $class->discriminatorMap, true) === false) {
+        if (! $class->isInheritanceTypeNone() && ! $class->isRootEntity() && ($class->reflClass !== null && ! $class->reflClass->isAbstract()) && ! $class->isMappedSuperclass && array_search($class->name, $class->discriminatorMap, true) === false) {
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Tools/SchemaValidator.php]: At what point should we use linebreaks :joy: ?

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
thanks @mpdude!
