### PR TITLE
Include `ON DELETE CASCADE` associations in the delete order computation

### LINKED ISSUE #10348: Order of referenced child deletions not correct when referencing to itself
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.14.0

#### Summary

The order in which the UoW wants to delete children is somehow missing a dependency when there is an association to the same class even if you specified `cascade: ['remove']`.
Given you have

- Parent -> has an association to children with `cascade: ['remove']`
- Child 1
- Child 2 -> has an association to Child 1 with `cascade: ['remove']`.

Now you delete the parent.
Doctrine tries to remove Child 1 first instead of Child 2 causing a foreign constraint violation: 

> Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`test`.`child_entities`, CONSTRAINT `FK_DAEB194156A273CC` FOREIGN KEY (`origin_id`) REFERENCES `child_entities` (`id`))

#### How to reproduce

I've created a test setup because I'm not familiar with the internals of ORM at all. So here we go:

1. Clone https://github.com/Toflar/doctrine-orm-bug-reproducer
2. Run `composer install`
3. Adjust dummy mysql connection example in `bootstrap.php`.
4. Run `bin/doctrine orm:schema-tool:drop --force && bin/doctrine orm:schema-tool:create`
5. Run `php test.php`.

#### Expected behavior

It should not throw an exception. Doctrine should remove Child 2 first.

### PR DESCRIPTION
**Pull request by mpdude**
In order to resolve #10348, some changes were included in #10547 to improve the computed _delete_ order for entities. 

One assumption was that foreign key references with `ON DELETE SET NULL` or `... CASCADE` need not need to be taken into consideration when planning the deletion order, since the RDBMS would unset or cascade-delete such associations by itself when necessary. Only associations that do _not_ use RDBMS-level cascade handling would be sequenced, to make sure the referring entity is deleted before the referred-to one.

This assumption is wrong for `ON DELETE CASCADE`. The following examples give reasons why we need to also consider such associations, and in addition, we need to be able to deal with cycles formed by them.

In the following diagrams, `odc` means `ON DELETE CASCADE`, and `ref` is a regular foreign key with no extra `ON DELETE` semantics.

```mermaid
graph LR;
C-->|ref| B;
B-->|odc| A;
```

In this example, C must be removed before B and A. If we ignore the B->A dependency in the delete order computation, the result may not to be correct. ACB is not a working solution.

```mermaid
graph LR;
A-->|odc| B;
B-->|odc| A;
C-->|ref| B;
```

This is the situation in #10912. We have to deal with a cycle in the graph. C must be removed before A as well as B. If we ignore the B->A dependency (e.g. because we set it to "optional" to get away with the cycle), we might end up with an incorrect order ACB.

```mermaid
graph LR;
A-->|odc| B;
B-->|odc| A;
A-->|ref| C;
C-->|ref| B;
```

This example has no possible remove order. But, if we treat `odc` edges as optional, A -> C -> B would wrongly be deemed suitable.

```mermaid
graph LR;
A-->|ref| B;
B-->|odc| C;
C-->|odc| B;
D-->|ref| C;
```

Here, we must first remove A and D in any order; then, B and C in any order. If we treat one of the `odc` edges as optional, we might find the invalid solutions ABDC or DCAB.

#### Solution implemented in this PR

First, build a graph with a node for every to-be-removed entity, and edges for `ON DELETE CASCADE` associations between those entities. Then, use [Tarjan's algorithm](https://en.wikipedia.org/wiki/Tarjan%27s_strongly_connected_components_algorithm) to find strongly connected components (SCCs) in this graph. The significance of SCCs is that whenever we remove one of the entities in a SCC from the database (no matter which one), the DBMS will immediately remove _all_ the other entities of that group as well.

For every SCC, pick one (arbitrary) entity from the group to represent all entities of that group. 

Then, build a second graph. Again we have nodes for all entities that are to be removed. This time, we insert edges for all regular (foreign key) associations and those with `ON DELETE CASCADE`. `ON DELETE SET NULL` can be left out. The edges are not added between the entities themselves, but between the entities representing the respective SCCs.

Also, for all non-trivial SCCs (those containing more than a single entity), add dependency edges to indicate that all entities of the SCC shall be processed _after_ the entity representing the group. This is to make sure we do not remove a SCC inadvertedly by removing one of its entities too early.

Run a topological sort on the second graph to get the actual delete order. Cycles in this second graph are a problem, there is no delete order.

Fixes #10912.

### CODE REVIEW

**Comment by mpdude** [comment]
X-ref #9376

**Comment by Dallas62** [comment]
Hi @mpdude,
Do you have an ETA on the landing of this fix ?
Thanks !

**Comment by mpdude** [comment]
@Dallas62 Could you please try the change suggested in this PR?

File: lib/Doctrine/ORM/Internal/StronglyConnectedComponents.php [hunk 1]
```diff
@@ -0,0 +1,166 @@
...
+    private $maxdfs = 0;
+
+    /**
+     * Nodes representing the SCC another node is in, indexed by lookup-node object ID
+     *
+     * @var array<int, object>
+     */
+    private $representingNodes = [];
+
+    /** @var array<int> */
```
Comment (greg0ire) [inline lib/Doctrine/ORM/Internal/StronglyConnectedComponents.php]:
```suggestion
    /** @var list<int> */
```

Should there also be a note about what `int` represents here?

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH10912Test.php [hunk 2]
```diff
@@ -0,0 +1,166 @@
...
+        $this->_em->remove($profile);
+        $this->_em->remove($user);
+        $this->_em->remove($room);
+
+        $queryLog = $this->getQueryLog();
+        $queryLog->reset()->enable();
+
+        $this->_em->flush();
+
+        $queries = array_values(array_filter($queryLog->queries, static function ($entry) {
```
Comment (greg0ire) [inline tests/Doctrine/Tests/ORM/Functional/Ticket/GH10912Test.php]:
```suggestion
        $queries = array_values(array_filter($queryLog->queries, static function (array $entry): bool {
```

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH10912Test.php [hunk 3]
```diff
@@ -0,0 +1,166 @@
...
+            return strpos($entry['sql'], 'DELETE') === 0;
+        }));
+
+        self::assertCount(3, $queries);
+
+        // $room deletion is the first query
```
Comment (greg0ire) [inline tests/Doctrine/Tests/ORM/Functional/Ticket/GH10912Test.php]: This comment could be converted to a `$message` argument to `assertSame`

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH10913Test.php [hunk 4]
```diff
@@ -0,0 +1,167 @@
...
+    }
+
+    private function flushAndAssertNumberOfDeleteQueries(int $expectedCount): void
+    {
+        $queryLog = $this->getQueryLog();
+        $queryLog->reset()->enable();
+
+        $this->_em->flush();
+
+        $queries = array_values(array_filter($queryLog->queries, static function ($entry) {
```
Comment (greg0ire) [inline tests/Doctrine/Tests/ORM/Functional/Ticket/GH10913Test.php]:
```suggestion
        $queries = array_values(array_filter($queryLog->queries, static function (array $entry): bool {
```

**Comment by mpdude** [comment]
Feedback addressed

**Review by greg0ire — APPROVED** [review]
Looks good to me 👍
More than that, it was a very interesting read! Thanks for all the effort you put in this!
