### PR TITLE
Fix parameter name comparison in AbstractQuery regarding different types (fixes #6699)

### LINKED ISSUE #6699: setParameter issue when mixing :name and ?0 syntax
Example:
```php
$queryBuilder

    ->andWhere("alias.field = :paramname")
    ->setParameter('paramname', $paramval)

    ->andWhere("alias.field = ?0")
    ->setParameter(0, $paramval)

;
```

If I call `getParameters()`, only 1 param is returned.

When executing the query, an exception is thrown:

> Too few parameters: the query defines 2 parameters but you only bound 1

This seems to happen only if the param is named `?0`.
With `?1`, it seems to be ok.

### PR DESCRIPTION
**Pull request by Majkl578**
AbstractQuery::setParameter() uses weak comparison to compare parameter names and decide whether to update existing or add new parameter. AbstractQuery::getParameter() does so as well.
This is problematic for parameter named `0` since strings are downcasted to `0` as well, making it incorrectly assume that i.e. the `0` and `"foo"` are the same parameter.
In most cases, cast is not needed and we would ideally want to prevent it, thus added identity check first and only if it fails, string cast comparison is attempted.

Fixes #6699.

### CODE REVIEW

**Comment by Majkl578** [comment]
Reworded & fix + more tests added.

**Comment by Seb33300** [comment]
You have only updated the `AbstractQuery::setParameter()` function but I can find the exact same function in `QueryBuilder`: https://github.com/doctrine/doctrine2/blob/80f7824b3d8a2b5e3810c597582ee3524750b682/lib/Doctrine/ORM/QueryBuilder.php#L533 
Not sure if it should be modified too.

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH6699Test.php [hunk 1]
```diff
@@ -0,0 +1,38 @@
+<?php
+
+namespace Doctrine\Tests\ORM\Functional\Ticket;
+
+use Doctrine\Tests\Models\CMS\CmsUser;
+use Doctrine\Tests\OrmFunctionalTestCase;
+
+/**
+ * @group #6699
```
Comment (lcobucci) [inline tests/Doctrine/Tests/ORM/Functional/Ticket/GH6699Test.php]: We're using the ticket id without the `#` everywhere else, we should keep it consistent here too

File: tests/Doctrine/Tests/ORM/Query/QueryTest.php [hunk 2]
```diff
@@ -303,4 +304,65 @@ public function testSelectFromSubquery()
         $this->expectExceptionMessage('Subquery');
         $query->getSQL();
     }
+
+    /**
+     * @group #6699
```
Comment (lcobucci) [inline tests/Doctrine/Tests/ORM/Query/QueryTest.php]: We're using the ticket id without the `#` everywhere else, we should keep it consistent here too

File: tests/Doctrine/Tests/ORM/Query/QueryTest.php [hunk 3]
```diff
@@ -303,4 +304,65 @@ public function testSelectFromSubquery()
...
+        $query = $this->_em->createQuery('select u from ' . CmsUser::class . ' u where u.id = ?0');
+
+        $query->setParameter(0, 0);
+
+        $this->assertSame(0, $query->getParameter(0)->getValue());
+        $this->assertSame(0, $query->getParameter('0')->getValue());
+    }
+
+    /**
+     * @group #6699
```
Comment (lcobucci) [inline tests/Doctrine/Tests/ORM/Query/QueryTest.php]: We're using the ticket id without the `#` everywhere else, we should keep it consistent here too

File: tests/Doctrine/Tests/ORM/Query/QueryTest.php [hunk 4]
```diff
@@ -303,4 +304,65 @@ public function testSelectFromSubquery()
...
+        $query->setParameter(0, 0);
+        $query->setParameter('name', 'Doctrine');
+
+        $this->assertSame(2, $query->getParameters()->count());
+        $this->assertSame(0, $query->getParameter('0')->getValue());
+        $this->assertSame('Doctrine', $query->getParameter('name')->getValue());
+    }
+
+    /**
+     * @group #6699
```
Comment (lcobucci) [inline tests/Doctrine/Tests/ORM/Query/QueryTest.php]: We're using the ticket id without the `#` everywhere else, we should keep it consistent here too

File: tests/Doctrine/Tests/ORM/Query/QueryTest.php [hunk 5]
```diff
@@ -303,4 +304,65 @@ public function testSelectFromSubquery()
...
+        $query->setParameter('name', 'Doctrine');
+        $query->setParameter(0, 0);
+
+        $this->assertSame(2, $query->getParameters()->count());
+        $this->assertSame(0, $query->getParameter(0)->getValue());
+        $this->assertSame('Doctrine', $query->getParameter('name')->getValue());
+    }
+
+    /**
+     * @group #6699
```
Comment (lcobucci) [inline tests/Doctrine/Tests/ORM/Query/QueryTest.php]: We're using the ticket id without the `#` everywhere else, we should keep it consistent here too

File: tests/Doctrine/Tests/ORM/Query/QueryTest.php [hunk 6]
```diff
@@ -303,4 +304,65 @@ public function testSelectFromSubquery()
...
+    public function testSetParameterWithTypeJugglingWorks()
+    {
+        $query = $this->_em->createQuery("select u from Doctrine\Tests\Models\CMS\CmsUser u where u.id != ?0 and u.username = :name");
+
+        $query->setParameter('0', 1);
+        $query->setParameter('name', 'Doctrine');
+        $query->setParameter(0, 2);
+        $query->setParameter('0', 3);
+
+        $this->assertSame(2, $query->getParameters()->count());
```
Comment (lcobucci) [inline tests/Doctrine/Tests/ORM/Query/QueryTest.php]: `self::assertCount()` would be more appropriated here

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH6699Test.php [hunk 7]
```diff
@@ -0,0 +1,38 @@
...
+            ->andWhere('u.username = :username')
+            ->andWhere('u.id = ?0');
+        $query = $qb->getQuery();
+
+        $query->setParameter('username', 'bar');
+        $query->setParameter(0, 0);
+
+        $query->execute();
+
+        $this->assertSame(2, $query->getParameters()->count());
```
Comment (lcobucci) [inline tests/Doctrine/Tests/ORM/Functional/Ticket/GH6699Test.php]: `self::assertCount()` would be more appropriated here

File: tests/Doctrine/Tests/ORM/Query/QueryTest.php [hunk 8]
```diff
@@ -303,4 +304,65 @@ public function testSelectFromSubquery()
...
+     * @group #6699
+     */
+    public function testSetParameterWithNameZeroIsNotOverridden() : void
+    {
+        $query = $this->_em->createQuery('select u from ' . CmsUser::class . ' u where u.id != ?0 and u.username = :name');
+
+        $query->setParameter(0, 0);
+        $query->setParameter('name', 'Doctrine');
+
+        $this->assertSame(2, $query->getParameters()->count());
```
Comment (lcobucci) [inline tests/Doctrine/Tests/ORM/Query/QueryTest.php]: `self::assertCount()` would be more appropriated here

File: tests/Doctrine/Tests/ORM/Query/QueryTest.php [hunk 9]
```diff
@@ -303,4 +304,65 @@ public function testSelectFromSubquery()
...
+     * @group #6699
+     */
+    public function testSetParameterWithNameZeroDoesNotOverrideAnotherParameter() : void
+    {
+        $query = $this->_em->createQuery('select u from ' . CmsUser::class . ' u where u.id != ?0 and u.username = :name');
+
+        $query->setParameter('name', 'Doctrine');
+        $query->setParameter(0, 0);
+
+        $this->assertSame(2, $query->getParameters()->count());
```
Comment (lcobucci) [inline tests/Doctrine/Tests/ORM/Query/QueryTest.php]: `self::assertCount()` would be more appropriated here

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH6699Test.php [hunk 10]
```diff
@@ -0,0 +1,38 @@
...
+{
+    protected function setUp()
+    {
+        $this->useModelSet('cms');
+        parent::setUp();
+    }
+
+    public function testMixedParametersWithZeroNumber()
+    {
+        $qb = $this->_em->createQueryBuilder()
```
Comment (lcobucci) [inline tests/Doctrine/Tests/ORM/Functional/Ticket/GH6699Test.php]: We can simplify this bit, since the query builder reference is not really needed, like:

```php
$query = $this->_em->createQueryBuilder()
                   ->select('u')
                   ->from(CmsUser::class, 'u')
                   ->andWhere('u.username = :username')
                   ->andWhere('u.id = ?0')
                   ->getQuery();
```

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH6699Test.php [hunk 11]
```diff
@@ -0,0 +1,38 @@
...
+ */
+class GH6699Test extends OrmFunctionalTestCase
+{
+    protected function setUp()
+    {
+        $this->useModelSet('cms');
+        parent::setUp();
+    }
+
+    public function testMixedParametersWithZeroNumber()
```
Comment (lcobucci) [inline tests/Doctrine/Tests/ORM/Functional/Ticket/GH6699Test.php]: ` : void`

File: tests/Doctrine/Tests/ORM/Functional/Ticket/GH6699Test.php [hunk 12]
```diff
@@ -0,0 +1,38 @@
...
+
+use Doctrine\Tests\Models\CMS\CmsUser;
+use Doctrine\Tests\OrmFunctionalTestCase;
+
+/**
+ * @group #6699
+ */
+class GH6699Test extends OrmFunctionalTestCase
+{
+    protected function setUp()
```
Comment (lcobucci) [inline tests/Doctrine/Tests/ORM/Functional/Ticket/GH6699Test.php]: ` : void`

File: tests/Doctrine/Tests/ORM/Query/QueryTest.php [hunk 13]
```diff
@@ -303,4 +304,65 @@ public function testSelectFromSubquery()
...
+        $this->assertSame(0, $query->getParameter(0)->getValue());
+        $this->assertSame('Doctrine', $query->getParameter('name')->getValue());
+    }
+
+    /**
+     * @group #6699
+     */
+    public function testSetParameterWithTypeJugglingWorks()
```
Comment (lcobucci) [inline tests/Doctrine/Tests/ORM/Query/QueryTest.php]: ` : void`

File: tests/Doctrine/Tests/ORM/Query/QueryTest.php [hunk 14]
```diff
@@ -303,4 +304,65 @@ public function testSelectFromSubquery()
...
+    {
+        $query = $this->_em->createQuery("select u from Doctrine\Tests\Models\CMS\CmsUser u where u.id != ?0 and u.username = :name");
```
Comment (lcobucci) [inline tests/Doctrine/Tests/ORM/Query/QueryTest.php]: Could use `' . CmsUser::class . '` to keep consistency

**Review by lcobucci — CHANGES_REQUESTED** [review]
Some nitpicking, as usual 😂 
We should also use `self::assert*()` everywhere.

I got some time now so I can apply the changes and investigate any performance impact, if you don't mind.

File: lib/Doctrine/ORM/AbstractQuery.php [hunk 15]
```diff
@@ -369,17 +369,10 @@ public function setParameters($parameters)
      */
     public function setParameter($key, $value, $type = null)
     {
-        $filteredParameters = $this->parameters->filter(
```
[the remark this answers is not in the document]
Comment (lcobucci) [reply lib/Doctrine/ORM/AbstractQuery.php]: Just tested, the answer is: we have no performance impact

**Review by lcobucci — APPROVED** [review]

**Comment by lcobucci** [comment]
@Majkl578 🚢 and backported to `v2.5.x`

Thanks!

**Comment by Majkl578** [comment]
We should probably copy this behavior to AbstractQuery::setParameter() as well (thanks for spotting @Seb33300).
For 3.0 we should consider different approach - I was already thinking about having ParameterCollection or ParameterBag (Symfony-style naming).

**Comment by lcobucci** [comment]
> We should probably copy this behavior to AbstractQuery::setParameter() as well (thanks for spotting @Seb33300).

I've applied it there as well

**Comment by Majkl578** [comment]
@lcobucci Cool, thanks!
