### PR TITLE
SchemaValidator: Changing mapping of BIGINT to string|int

### LINKED ISSUE #11377: SchemaValidator is complaining about BIGINT with PHP typehint `int`
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1.0 and DBAL 4.0.1

#### Summary

With this mapping:
```php
#[ORM\Column(type: Types::BIGINT, nullable: true)]
private ?int $foo = null;
```
... Symfony Profiler is reporting a Mapping Error:

> The field 'Bar#foo' has the property type 'int' that differs from the metadata field type 'string' returned by the 'bigint' DBAL type.

Which is *kinda* right according to the docs at https://www.doctrine-project.org/projects/doctrine-dbal/en/4.0/reference/types.html#bigint :

> Values retrieved from the database are always converted to PHP's integer type if they are within PHP's integer range or string if they aren't.

But according to https://github.com/doctrine/orm/issues/11073#issuecomment-1822464292 , a BIGINT should be typehinted as `int`:

> Then before migrating to 4.0.0, you change the type to string|int, ignore the warning, and **change to int after the migration.**

So what is the recommended typehint now?

I think there should be a recommendation in the docs, maybe I can add it to https://github.com/doctrine/dbal/pull/6336

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Closes https://github.com/doctrine/orm/issues/11377
Follow-up of https://github.com/doctrine/orm/pull/11396

I just copied the `const`, so it can be deleted again easily, once DBAL 3 is no longer supported.

* How can I check DBAL 3 in the test?
* Besides that, is the test enough or should I test more scenarios (positive *and* negative)?

### CODE REVIEW

**Comment by greg0ire** [comment]
> How can I check DBAL 3 in the test

Same way you did in the code.

> Besides that, is the test enough or should I test more scenarios (positive and negative)?

I think a test testing what happens when using just `int` would be nice to have.


Also, it seems there are CI jobs failing. Please take a look at [this guide](https://www.doctrine-project.org/contribute/#dealing-with-checks-and-tools) for more on how to handle those.

**Comment by ThomasLandauer** [comment]
OK, I also added another test for just `string`.

What I don't understand: `composer install` gave me DBAL 4. So where/when is the situation with DBAL 3 ever tested? If the line `if (method_exists(BigIntType::class, 'getName'))` is not doing what we hope it does (e.g. is always false), then the test will not detect it (since it uses the same logic as the code).

**Comment by greg0ire** [comment]
This step allows us to test with DBAL 3: https://github.com/doctrine/orm/blob/9c560713925ac5859342e6ff370c4c997acf2fd4/.github/workflows/continuous-integration.yml#L73-L75

thanks to this: https://github.com/doctrine/orm/blob/9c560713925ac5859342e6ff370c4c997acf2fd4/.github/workflows/continuous-integration.yml#L39-L41

If the version detection code is wrong, then the test should fail because it will expect the wrong thing to happen.

File: tests/Tests/ORM/Tools/SchemaValidatorTest.php [hunk 1]
```diff
@@ -228,6 +232,51 @@ public function testInvalidAssociationTowardsMappedSuperclass(): void
...
+    public function testBigintMappedToStringInt(): void
+    {
+        $class = $this->em->getClassMetadata(BigintMappedToStringInt::class);
+        $ce    = $this->validator->validateClass($class);
+
+        if (method_exists(BigIntType::class, 'getName')) { // DBAL 3
+            $this->assertEquals([], $ce);
+        } else { // DBAL 4+
+            $this->assertEquals([], $ce);
+        }
```
Comment (greg0ire) [inline tests/Tests/ORM/Tools/SchemaValidatorTest.php]: … why are you using a condition here? It's the same code.

Comment (ThomasLandauer) [reply tests/Tests/ORM/Tools/SchemaValidatorTest.php]: Well. too much copy-pasted... ;-)

**Comment by greg0ire** [comment]
Pleas squash your commits.

**Comment by ThomasLandauer** [comment]
OK, done :-)

**Review by beberlei — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @ThomasLandauer !

**Comment by derrabus** [comment]
Thank you very much for your work on this topic, @ThomasLandauer. However, we've decided to revert your patch in favor of #11414.
