### PR TITLE
Address deprecations

### LINKED ISSUE #12119: False positive for "Using nullable columns (xxx) in a primary key index is deprecated."?
### Bug Report

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 4.3.2

#### Summary

When running PHPUnit tests it shows false-positive deprecation warnings triggered by DBAL. I hope this is the correct repository, because this currently happens when also using Doctrine.

Ref: https://github.com/doctrine/dbal/pull/6787

#### Current behavior

It triggers deprecation warnings, even though related tables don't match the criteria.

Image

Here as text:

```
Remaining indirect deprecation notices (4)

  1x: Using nullable columns (GeoEintragTeilVonBeziehungVonEintrag.geoeintragteilvonbeziehung_id) in a primary key index is deprecated. (Table.php:182 called by Table.php:199, https://github.com/doctrine/dbal/pull/6787, package doctrine/dbal)
    1x in DemoTest::test from Tests

  1x: Using nullable columns (GeoEintragTeilVonBeziehungVonEintrag.geoeintrag_id) in a primary key index is deprecated. (Table.php:182 called by Table.php:199, https://github.com/doctrine/dbal/pull/6787, package doctrine/dbal)
    1x in DemoTest::test from Tests

  1x: Using nullable columns (GeoEintragTeilVonBeziehungZuEintrag.geoeintragteilvonbeziehung_id) in a primary key index is deprecated. (Table.php:182 called by Table.php:199, https://github.com/doctrine/dbal/pull/6787, package doctrine/dbal)
    1x in DemoTest::test from Tests

  1x: Using nullable columns (GeoEintragTeilVonBeziehungZuEintrag.geoeintrag_id) in a primary key index is deprecated. (Table.php:182 called by Table.php:199, https://github.com/doctrine/dbal/pull/6787, package doctrine/dbal)
    1x in DemoTest::test from Tests
```

All mentioned columns are being defined as `NOT NULL`, for instance:

Image

#### Expected behavior

No deprecation warnings at all.

#### How to reproduce

I added a reproducer:

https://github.com/k00ni/dbal-nullable-columns-primary-key

There is a basic workflow to demonstrate the deprecations:

https://github.com/k00ni/dbal-nullable-columns-primary-key/actions/runs/16804524077/job/47593473139#step:9:127

### PR DESCRIPTION
**Pull request by greg0ire**
By [deprecating the usage of nullable columns as part of a primary key](https://github.com/doctrine/dbal/pull/6787), `doctrine/dbal` 4.3 points out several bad defaults in the ORM:

- by default, columns in an n-m table are nullable;
- by default, columns representing a to-one relationship that are part of a primary key are nullable.

Let us change the minimum amount of bad defaults, while still allowing people to explicitly request a join column be nullable.

On 3.6.x, we should deprecate setting `nullable` in the above cases, and on 4.0.x, we should throw when that's the case.

### CODE REVIEW

File: src/Mapping/JoinColumnProperties.php [hunk 1]
```diff
@@ -12,7 +12,7 @@ public function __construct(
         public readonly string|null $referencedColumnName = null,
         public readonly bool $deferrable = false,
         public readonly bool $unique = false,
-        public readonly bool $nullable = true,
+        public readonly bool|null $nullable = null,
```
Comment (morozov) [inline src/Mapping/JoinColumnProperties.php:15]: Isn't the fact that now this property can contain null a breaking change? I don't really like that a seemingly boolean property is now nullable. Instead, a separate flag could be introduced like `$wasNullableSetExplicitly` (well, unfortunately, it's a public property that can be modified w/o triggering any code).

File: UPGRADE.md [hunk 2]
```diff
@@ -1,3 +1,53 @@
+# Upgrade to 3.5.2
+
+## Bugfix: to-one referencing columns involved in a primary key are no longer nullable by default
+
+By default, columns used to establish a to-one relationship that were also part
+of the primary key used to be marked as nullable. This makes no sense, was a bug,
+and has been fixed.
+If you want to delay the migration to the new behavior, you can explicitly mark
+the column as nullable in your mapping.
```
Comment (morozov) [inline UPGRADE.md]: Doesn't this also mean that unless the user opts out of the fixed behavior, the behavior will change, so it's a breaking change.

FWIW, the DBAL will mutate this column and make it nullable and also create a non-nullable column in the database. At this point, it's not clear why exactly someone might want to opt out and why.

**Review by morozov — COMMENTED** [review]
Directionally, the change looks right to me. I'm only unsure about the BC impact. It would be nice to enumerate some typical use cases (e.g. when someone wants to opt out) and see why and what the upgrade will look like.

If it's a bug (which I agree it is), then maybe we don't need to provide the way to retain the incorrect behavior.

File: src/Mapping/JoinColumnProperties.php (hunk 1 above)
Comment (greg0ire) [reply src/Mapping/JoinColumnProperties.php:15]: Yes, that's exactly the issue. And with PHP, I don't know of a way to detect that a named argument was explicitly set: https://3v4l.org/uesWA#v8.4.9

File: UPGRADE.md (hunk 2 above)
Comment (greg0ire) [reply UPGRADE.md]: Yes, it's a breaking change, and that's why I want to provide the user with a way to opt out, although I am not sure it will be useful at all; maybe they have some big table on which they want to delay the migration, in order to do it in a different way, with a different tool than the one they use for other tables.

**Comment by greg0ire** [comment]
> maybe we don't need to provide the way to retain the incorrect behavior.

I plan to nudge users into switching to the correct behavior in 3.6.x, with a deprecation. I think since I'm doing a breaking change in a patch release, I should allow people to opt out of the change.

File: UPGRADE.md (hunk 2 above)
Comment (morozov) [reply UPGRADE.md]: I don't think a schema migration will be necessary after the upgrade to the new ORM version. DBAL 4 will still make the PK columns non-nullable, regardless of what the metadata says.

Comment (greg0ire) [reply UPGRADE.md]: Oh! I didn't realize that! Then I guess this makes this a lot less of a breaking change, doesn't it? And it also mean we indeed don't need to provide users with a way to opt out of this.

File: UPGRADE.md [hunk 3]
```diff
@@ -1,3 +1,53 @@
+# Upgrade to 3.5.2
```
Comment (derrabus) [inline UPGRADE.md]: The fact that we need to mention this change in the upgrade file tells me that this kind of change should go into a x.y.0 release.

Comment (greg0ire) [reply UPGRADE.md]: You often insist on having deprecations being treated as bugs and addressed in the patch branch. Are you maybe suggesting we use https://github.com/doctrine/deprecations?tab=readme-ov-file#suppressing-specific-deprecations for this one, then retarget this?

File: UPGRADE.md (hunk 2 above)
Comment (morozov) [reply UPGRADE.md]: It sounds right. FWIW, here's the [test](https://github.com/doctrine/dbal/pull/6787/files#diff-a9e6eb632904e1a48e50c32b48430e910ca9cec1702c8c6d1c1221401ef65509R309) that demonstrates that DBAL 4 will make the PK columns non-nullable, regardless of what the metadata says.

File: UPGRADE.md (hunk 3 above)
Comment (derrabus) [reply UPGRADE.md]: > You often insist on having deprecations being treated as bugs and addressed in the patch branch.

I do. But you're about to change external behavior. Let's not do that in a bugfix release.

> Are you maybe suggesting we use https://github.com/doctrine/deprecations?tab=readme-ov-file#suppressing-specific-deprecations for this one, then retarget this?

Not sure if suppressing the deprecation is worth it, tbh.

Comment (greg0ire) [reply UPGRADE.md]: OK. Given what has been said in other threads, I'm rather going to remove this upgrade guide as well as the possibility to opt-out of this change since it will not result in a database change after all.

Comment (derrabus) [reply UPGRADE.md]: It doesn't? Then I'm fine targeting 3.5.x. 🙂

**Review by morozov — APPROVED** [review]
I'm not that well familiar with the ORM to provide a meaningful feedback. I'm fine with this change as long as other maintainers are.

File: src/Mapping/JoinColumnProperties.php (hunk 1 above)
Comment (SenseException) [reply src/Mapping/JoinColumnProperties.php:15]: I don't know the impact of this change on the projects, that are all out there when they update ORM. Hard for me to assess.

**Review by derrabus — APPROVED** [review]

File: src/Mapping/JoinColumnProperties.php (hunk 1 above)
Comment (greg0ire) [reply src/Mapping/JoinColumnProperties.php:15]: @SenseException let me point out one thing: I did not have to change a single functional test.
