### PR TITLE
Avoid lazy object initialization when initializing read-only property

### LINKED ISSUE #12166: bug in readonly properties & native lazy objects, triggers immedtiately
Just found another bug with the readonly IDs and new PHP 8.4 ghost objects - if the ID is readonly of a related entity - when it tries to create a proxy for that related entity - the proxy is immediately initialized from the ReadonlyAccessor - it calls the reflection property->isInitialized on the ID and this triggers the initialization in the foreach right after the proxy generation. Here is the stacktrace from inside of the ghost object function to visualize which flow triggered the initialization.

image

This cascades to a very ugly and hard to trace bug - it sets the `originalEntityData` to empty array, which then behind the scenes ignores all changes made on that entity on flush. Just spent like 3 hours debugging to find that out. Also couldn't use debugger to trace that issue, because the xdebug itself triggers the initialization of entities so manual logs until my head spins..

_Originally posted by @vuryss in https://github.com/doctrine/doctrine-website/pull/479#issuecomment-3292973817_

### PR DESCRIPTION
**Pull request by greg0ire**
Initializing e.g. a readonly ID does not require loading any data from
the database. However, calling isInitialized() on the reflection of a
readonly property triggers the native lazy object initialization.
If we have a lazy property at hand, then the property cannot be initialized
already, so it is safe to skip the call.

Fixes #12166

### CODE REVIEW

File: tests/Tests/ORM/Functional/Ticket/GH12166/GH12166Test.php [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+use Doctrine\Tests\OrmFunctionalTestCase;
+use PHPUnit\Framework\Attributes\RequiresPhp;
+
+#[RequiresPhp('>= 8.4.0')]
+class GH12166Test extends OrmFunctionalTestCase
+{
+    public function testProxyWithReadonlyIdIsNotInitializedImmediately(): void
+    {
+        if (! $this->_em->getConfiguration()->isNativeLazyObjectsEnabled()) {
+            $this->markTestSkipped('Property hooks require native lazy objects to be enabled.');
```
Comment (stof) [inline tests/Tests/ORM/Functional/Ticket/GH12166/GH12166Test.php]: This skipping looks weird to me. This test does not rely on property hooks

File: tests/Tests/ORM/Functional/Ticket/GH12166/GH12166Test.php [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+        $reflClass = $this->_em->getClassMetadata(LazyEntityWithReadonlyId::class)->reflClass;
+        self::assertTrue(
+            $reflClass->isUninitializedLazyObject($proxy),
+            'Proxy should remain uninitialized after creation',
+        );
+
+        $id = $proxy->getId();
+        self::assertSame(123, $id);
+        self::assertTrue(
+            $reflClass->isUninitializedLazyObject($proxy),
```
Comment (stof) [inline tests/Tests/ORM/Functional/Ticket/GH12166/GH12166Test.php]: Using the dedicated method of the base test case should allow making this test compatible with old proxy systems

File: tests/Tests/ORM/Functional/Ticket/GH12166/GH12166Test.php [hunk 3]
```diff
@@ -0,0 +1,34 @@
+<?php
+
+declare(strict_types=1);
+
+namespace Doctrine\Tests\ORM\Functional\Ticket\GH12166;
+
+use Doctrine\Tests\OrmFunctionalTestCase;
+use PHPUnit\Framework\Attributes\RequiresPhp;
+
+#[RequiresPhp('>= 8.4.0')]
```
Comment (stof) [inline tests/Tests/ORM/Functional/Ticket/GH12166/GH12166Test.php]: This should not be necessary anymore if we execute the test with all proxy implementations

**Review by SenseException — DISMISSED** [review]
This is okay for handling the lazy-loading, but if I remove your newly added code, the test fails with a message like "no such table: gh12166_lazy_entity", because it tries to access a table that doesn't exist (and doesn't need to since the test uses a Reference). This can be confusing if a regression happens during future development.

File: tests/Tests/ORM/Functional/Ticket/GH12166/GH12166Test.php (hunk 1 above)
Comment (greg0ire) [reply tests/Tests/ORM/Functional/Ticket/GH12166/GH12166Test.php]: Ah yes, sorry, I copied it from somewhere and failed to adapt the message.

**Comment by greg0ire** [comment]
> This is okay for handling the lazy-loading, but if I remove your newly added code, the test fails with a message like "no such table: gh12166_lazy_entity", because it tries to access a table that doesn't exist (and doesn't need to since the test uses a Reference). This can be confusing if a regression happens during future development.


Good point, addressed.

**Comment by stof** [comment]
Maybe this should use the `ReflectionProperty::isLazy` method, to skip this check check only for lazy properties, to avoid assigning values multiple times in readonly properties that are already initialized (which is the reason why this special access exists).

**Comment by greg0ire** [comment]
@stof I did not know about that method, thanks for pointing it out! It makes the code smaller, so I've combined both `if` statements into one, and it will further simplify in 4.0.x because we will be able to drop the PHP version id check.

I've also been able to remove the word "assume" from the commit message and PR description, which feels good.

**Comment by stof** [comment]
> I did not know about that method, thanks for pointing it out!

I just discovered now actually.

**Review by SenseException — APPROVED** [review]
